In [9]:
import os
os.environ['KAGGLE_USERNAME'] = "anastasiakhromova"
os.environ['KAGGLE_KEY'] = "KGAT_a4177bc6807822bc6d28ff5e23b1caff"
#!kaggle datasets download benjaminawd/new-york-times-articles-comments-2020

In [10]:
import pandas as pd 
import numpy as np

# EDA

In [11]:
data_path = "D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020"

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\2168738046.py:1: SyntaxWarning: invalid escape sequence '\P'
  data_path = "D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020"

In [12]:
test = pd.read_csv(data_path+'\\test.csv')
test

,newsdesk,section,subsection,material,headline,abstract,keywords,word_count,pub_date,is_popular,uniqueID
0,OpEd,Opinion,NaN,Op-Ed,Anyone Else Want to See Trump ‘Shut Up’?,Our president as a terrible toddler.,"['Presidential Election of 2020', 'Biden, Jose...",925,2020-10-01 00:05:51+00:00,1,nyt://article/e467c2ae-2df3-5836-a6ca-b23d0d33...
1,OpEd,Opinion,NaN,Op-Ed,Trump Calls on Extremists to ‘Stand By’,"Instead of condemning violent groups, the pres...","['Presidential Election of 2020', 'United Stat...",902,2020-10-01 00:43:28+00:00,1,nyt://article/9a7ef9e0-1334-56b2-a7f1-288c4887...
2,OpEd,Opinion,NaN,Op-Ed,"Can Mike Espy Make History, Again?",If the Democratic Party claims to value Black ...,"['Black People', 'Blacks', 'Presidential Elect...",1412,2020-10-01 00:45:17+00:00,1,nyt://article/4bb2b763-0088-5e10-b204-19e404f7...
3,Games,Crosswords & Games,NaN,News,In Which Rikishi Wear Mawashi,Adam Fromm is on the line.,['Crossword Puzzles'],849,2020-10-01 02:00:05+00:00,1,nyt://article/0d96205f-edb8-5f1f-8c44-1ddf6ed5...
4,Sports,Sports,Pro Football,News,N.F.L. Week 4 Predictions: Our Picks Against t...,Tom Brady and the Buccaneers are building mome...,"['Football', 'New England Patriots', 'Kansas C...",2690,2020-10-01 04:01:16+00:00,0,nyt://article/afc8295b-3c22-5a5f-9539-3f77b7b8...
...,...,...,...,...,...,...,...,...,...,...,...
3990,Editorial,Opinion,NaN,Op-Ed,What It Takes to Heal From Covid-19,"Survivors can get better, but they need help.","['Chronic Condition (Health)', 'Coronavirus (2...",1002,2020-12-31 15:27:47+00:00,1,nyt://article/e8adbb75-a8b3-5a8c-886b-b9c1195f...
3991,Sports,Sports,Baseball,News,Padres Jolt M.L.B. With Bold Moves to Set Up W...,While many teams continued to assess the finan...,"['San Diego Padres', 'Major League Baseball', ...",1100,2020-12-31 15:47:44+00:00,0,nyt://article/1f11417d-2c57-51b9-b75d-8f67f0a9...
3992,Business,Business Day,NaN,News,"Their Finances Ravaged, Customers Fear Banks W...",Banks have the power to decide whether to let ...,"['Banking and Financial Institutions', 'Corona...",1429,2020-12-31 16:21:40+00:00,1,nyt://article/c4b9edab-bdde-5d81-b496-06fedb52...
3993,Dining,Food,"Wine, Beer & Cocktails",News,Should Wine Be Among Your Health Resolutions?,The new category of ‘clean wines’ is an effort...,"['Wines', 'Grapes', 'Diet and Nutrition', 'Dia...",1307,2020-12-31 17:28:11+00:00,1,nyt://article/efcaf652-ffad-5b4e-9f17-4fd9aff5...
3994,Business,Technology,NaN,News,Microsoft Says Russian Hackers Viewed Some of ...,The hackers gained more access than the compan...,"['Microsoft Corp', 'US Federal Government Data...",340,2020-12-31 18:02:02+00:00,1,nyt://article/12048b2b-62e3-5bed-8c77-483a4299...

In [13]:
df_main = pd.read_csv('D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020\\nyt-articles-2020.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\3702147964.py:1: SyntaxWarning: invalid escape sequence '\P'
  df_main = pd.read_csv('D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020\\nyt-articles-2020.csv')

In [14]:
abstract = df_main[['abstract']]

In [15]:
for a in abstract.abstract[:5]:
    print(a)

Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.
Christina Iverson and Jeff Chen ring in the New Year.
All year long, Earth passes through streams of cosmic debris. Here’s a list of major meteor showers and how to spot one.
Never miss an eclipse, a meteor shower, a rocket launch or any other astronomical and space event that's out of this world.
A year full of highs and lows in space just ended, and the 12 months to come  will be full of new highlights in orbit and beyond.

## Tokenization

In [16]:
#!pip install spacy 
import spacy

In [17]:
#!pip install nltk

In [18]:
#import sys
#!{sys.executable} -m pip install spacy
#!{sys.executable} -m spacy download en_core_web_sm

In [19]:
nlp = spacy.load("en_core_web_sm")

In [20]:
abstract1 = abstract.abstract.iloc[0]
abstract1

'Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.'

In [21]:
with open("data\stopwords.txt", "r", encoding="utf-8") as f:
    stopwords = set(line.strip() for line in f)

print(stopwords)

{'such', 'not', 'me', 'has', 'then', 'herself', 'off', 'him', 'these', 'yourself', 'as', 'being', 'after', 'above', 'down', 'of', 't', 'very', 'more', 'at', 'other', 'they', 'through', 'have', 'does', 'hers', 'the', 's', 'whom', 'ourselves', 'all', 'did', 'once', 'because', 'to', 'your', 'only', 'if', 'which', 'each', 'and', 'it', 'their', 'our', 'been', 'can', 'we', 'myself', 'her', 'you', 'its', 'just', 'when', 'about', 'his', 'for', 'before', 'up', 'both', 'over', 'during', 'how', 'was', 'from', 'who', 'theirs', 'until', 'should', 'doing', 'most', 'some', 'itself', 'will', 'she', 'further', 'why', 'do', 'there', 'under', 'nor', 'on', 'are', 'while', 'were', 'them', 'no', 'or', 'in', 'having', 'be', 'against', 'out', 'himself', 'this', 'yourselves', 'own', 'but', 'too', 'am', 'again', 'that', 'don', 'is', 'below', 'those', 'a', 'with', 'than', 'my', 'what', 'same', 'i', 'yours', 'by', 'into', 'he', 'now', 'ours', 'an', 'here', 'so', 'between', 'themselves', 'where', 'few', 'had', 'any'}

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\2471722201.py:1: SyntaxWarning: invalid escape sequence '\s'
  with open("data\stopwords.txt", "r", encoding="utf-8") as f:

In [22]:
def preprocessing(document):
    
    try: 
        word_set = set()
        document = nlp(document)
        for word in document:
            lemma = word.lemma_.strip().lower()
        
            if (
                lemma
                and lemma not in stopwords
                and word.is_alpha
                and not word.is_punct
                and not word.is_space
            ):
                word_set.add(lemma)
        return word_set
    except:
        return set()

In [23]:
#abstract_reshape = preprocessing()

abstract["processed"] = abstract.abstract.apply(preprocessing)

C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\3746059958.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abstract["processed"] = abstract.abstract.apply(preprocessing)

In [24]:
abstract

,abstract,processed
0,Congress could do much more to protect America...,"{protect, serve, predatory, americans, congres..."
1,Christina Iverson and Jeff Chen ring in the Ne...,"{ring, year, jeff, iverson, chen, christina, new}"
2,"All year long, Earth passes through streams of...","{meteor, stream, year, shower, cosmic, major, ..."
3,"Never miss an eclipse, a meteor shower, a rock...","{meteor, shower, never, event, space, world, m..."
4,A year full of highs and lows in space just en...,"{year, low, end, month, highlight, space, high..."
...,...,...
16782,"Survivors can get better, but they need help.","{get, help, survivor, need, well}"
16783,While many teams continued to assess the finan...,"{diego, consequence, financial, world, become,..."
16784,Banks have the power to decide whether to let ...,"{overdrawn, whether, gain, account, bank, powe..."
16785,The new category of ‘clean wines’ is an effort...,"{try, seek, clean, healthful, effort, appeal, ..."
16786,The hackers gained more access than the compan...,"{code, company, reveal, email, modify, unable,..."

Jaccard similarity

In [68]:
def jaccard (words1:set, words2:set):
    intersection = words1.intersection(words2)
    union = words1.union(words2) 

    if len(union) == 0:
        jaccard_sim = 0
    else:
        jaccard_sim = round(len(intersection) /len(union), 5)
    return jaccard_sim

words1 = abstract.processed.iloc[10]
words2 = abstract.processed.iloc[10532]
jacsim1 = jaccard(words1, words2)

In [26]:
jacsim1

0.14286

In [27]:
type(abstract)

pandas.core.frame.DataFrame

In [44]:
def jaccard_sim_for_main (df:pd.DataFrame, number_main:int, top_k=5):
    main_abstract = df.processed.iloc[number_main]
    overall_jaccard_for_main = dict()
    for idxr, abstract in enumerate(df.processed):
        jacc_sim = jaccard(main_abstract, abstract)
        overall_jaccard_for_main[idxr] = jacc_sim

    overall_jaccard_for_main = sorted(
    overall_jaccard_for_main.items(),
    key=lambda x: x[1],
    reverse=True
    )[:top_k]
    return overall_jaccard_for_main

In [40]:
jaccard_sim_for_1 = jaccard_sim_for_main(abstract, 10)
jaccard_sim_for_1

[(10, 1.0), (2952, 0.15789), (10532, 0.14286), (2988, 0.10526), (2526, 0.1)]

In [63]:
def jaccard_total(df:pd.DataFrame, threshold = 0.2):
    jaccard_final = {}
    for article_idx, article in enumerate(df.processed):
        jaccard_sim_idx = jaccard_sim_for_main(df, article_idx, top_k=len(df))
        for pairs in jaccard_sim_idx:
            if (pairs[1] > threshold) and (pairs[1] < 1) and (pairs[0] > article_idx):
                jaccard_final[(article_idx, pairs[0])] = pairs[1]

    total_jaccard = sorted(
    jaccard_final.items(),
    key=lambda x: x[1],
    reverse=True
    )
    return total_jaccard

In [52]:
len(abstract)

16787

In [69]:
jaccard_total_d = jaccard_total(abstract)

In [71]:
jaccard_total_d

[((9248, 9852), 0.92857),
 ((9248, 11075), 0.92857),
 ((9852, 10762), 0.92857),
 ((10762, 11075), 0.92857),
 ((5724, 16679), 0.92308),
 ((387, 12219), 0.9),
 ((726, 12219), 0.9),
 ((1028, 12219), 0.9),
 ((2067, 12219), 0.9),
 ((2334, 12219), 0.9),
 ((2666, 12219), 0.9),
 ((3362, 12219), 0.9),
 ((3759, 12219), 0.9),
 ((4133, 12219), 0.9),
 ((4537, 12219), 0.9),
 ((4923, 12219), 0.9),
 ((5294, 12219), 0.9),
 ((5686, 12219), 0.9),
 ((6056, 12219), 0.9),
 ((6424, 12219), 0.9),
 ((6801, 12219), 0.9),
 ((7178, 12219), 0.9),
 ((7501, 12219), 0.9),
 ((12219, 12542), 0.9),
 ((12219, 12840), 0.9),
 ((12219, 13141), 0.9),
 ((12219, 13449), 0.9),
 ((12219, 13784), 0.9),
 ((12219, 14454), 0.9),
 ((12219, 14784), 0.9),
 ((12219, 15099), 0.9),
 ((12219, 15628), 0.9),
 ((12219, 15945), 0.9),
 ((58, 9253), 0.88889),
 ((58, 14458), 0.88889),
 ((58, 15947), 0.88889),
 ((3015, 9253), 0.88889),
 ((3015, 14458), 0.88889),
 ((3015, 15947), 0.88889),
 ((4533, 9253), 0.88889),
 ((4533, 14458), 0.88889),
 ((4533, 15947), 0.88889),
 ((7804, 9253), 0.88889),
 ((7804, 14458), 0.88889),
 ((7804, 15947), 0.88889),
 ((8144, 8446), 0.88889),
 ((8446, 8731), 0.88889),
 ((8446, 9015), 0.88889),
 ((8446, 9295), 0.88889),
 ((8446, 9598), 0.88889),
 ((8446, 9900), 0.88889),
 ((8144, 10202), 0.875),
 ((8144, 10510), 0.875),
 ((8144, 10807), 0.875),
 ((8731, 10202), 0.875),
 ((8731, 10510), 0.875),
 ((8731, 10807), 0.875),
 ((9015, 10202), 0.875),
 ((9015, 10510), 0.875),
 ((9015, 10807), 0.875),
 ((9295, 10202), 0.875),
 ((9295, 10510), 0.875),
 ((9295, 10807), 0.875),
 ((9598, 10202), 0.875),
 ((9598, 10510), 0.875),
 ((9598, 10807), 0.875),
 ((9900, 10202), 0.875),
 ((9900, 10510), 0.875),
 ((9900, 10807), 0.875),
 ((6712, 8960), 0.86667),
 ((406, 15964), 0.83333),
 ((406, 16411), 0.83333),
 ((4807, 15964), 0.83333),
 ((4807, 16411), 0.83333),
 ((12582, 12689), 0.83333),
 ((12975, 15964), 0.83333),
 ((12975, 16411), 0.83333),
 ((11796, 11988), 0.82353),
 ((5457, 12715), 0.81818),
 ((6843, 7169), 0.81818),
 ((6843, 7464), 0.81818),
 ((6843, 7778), 0.81818),
 ((4227, 5007), 0.8),
 ((4333, 4514), 0.8),
 ((9253, 14458), 0.8),
 ((9253, 15947), 0.8),
 ((13371, 13868), 0.8),
 ((8368, 8369), 0.78947),
 ((8368, 8370), 0.78947),
 ((8369, 8370), 0.78947),
 ((6429, 6430), 0.78571),
 ((6430, 6431), 0.78571),
 ((6430, 6432), 0.78571),
 ((6430, 6433), 0.78571),
 ((8880, 9433), 0.78571),
 ((9433, 9730), 0.78571),
 ((9433, 10034), 0.78571),
 ((9433, 10947), 0.78571),
 ((16007, 16058), 0.78571),
 ((58, 11638), 0.77778),
 ((88, 173), 0.77778),
 ((530, 15759), 0.77778),
 ((530, 16068), 0.77778),
 ((530, 16394), 0.77778),
 ((1855, 15759), 0.77778),
 ((1855, 16068), 0.77778),
 ((1855, 16394), 0.77778),
 ((2822, 15759), 0.77778),
 ((2822, 16068), 0.77778),
 ((2822, 16394), 0.77778),
 ((3015, 11638), 0.77778),
 ((3146, 15759), 0.77778),
 ((3146, 16068), 0.77778),
 ((3146, 16394), 0.77778),
 ((3511, 15759), 0.77778),
 ((3511, 16068), 0.77778),
 ((3511, 16394), 0.77778),
 ((3893, 15759), 0.77778),
 ((3893, 16068), 0.77778),
 ((3893, 16394), 0.77778),
 ((4533, 11638), 0.77778),
 ((5545, 6071), 0.77778),
 ((5545, 7372), 0.77778),
 ((5828, 15759), 0.77778),
 ((5828, 16068), 0.77778),
 ((5828, 16394), 0.77778),
 ((6207, 15759), 0.77778),
 ((6207, 16068), 0.77778),
 ((6207, 16394), 0.77778),
 ((7804, 11638), 0.77778),
 ((7915, 15759), 0.77778),
 ((7915, 16068), 0.77778),
 ((7915, 16394), 0.77778),
 ((8144, 8731), 0.77778),
 ((8144, 9015), 0.77778),
 ((8144, 9295), 0.77778),
 ((8144, 9598), 0.77778),
 ((8144, 9900), 0.77778),
 ((8359, 8360), 0.77778),
 ((8359, 8361), 0.77778),
 ((8359, 8362), 0.77778),
 ((8359, 8364), 0.77778),
 ((8359, 8365), 0.77778),
 ((8359, 8366), 0.77778),
 ((8359, 8367), 0.77778),
 ((8360, 8361), 0.77778),
 ((8360, 8362), 0.77778),
 ((8360, 8364), 0.77778),
 ((8360, 8365), 0.77778),
 ((8360, 8366), 0.77778),
 ((8360, 8367), 0.77778),
 ((8361, 8362), 0.77778),
 ((8361, 8364), 0.77778),
 ((8361, 8365), 0.77778),
 ((8361, 8366), 0.77778),
 ((8361, 8367), 0.77778),
 ((8362, 8364), 0.77778),
 ((8362, 8365), 0.77778),
 ((8362, 8366), 0.77778),
 ((8362, 8367), 0.77778),
 ((8364, 8365), 0.77778),
 ((8364, 8366), 0.77778),
 ((8364, 8367), 0.77778),
 ((8365, 8366), 0.77778),
 ((8365, 8367), 0.77778),
 ((8366, 8367), 0.77778),
 ((8446, 10202), 0.77778),
 ((8446, 10510), 0.77778),
 ((8446, 10807), 0.77778),
 ((8526, 15759), 0.77778),
 ((8526, 16068), 0.77778),
 ((8526, 16394), 0.77778),
 ((9096, 15759), 0.77778),
 ((9096, 16068), 0.77778),
 ((9096, 16394), 0.77778),
 ((9380, 15759), 0.77778),
 ((9380, 16068), 0.77778),
 ((9380, 16394), 0.77778),
 ((10355, 15759), 0.77778),
 ((10355, 16068), 0.77778),
 ((10355, 16394), 0.77778),
 ((10596, 15759), 0.77778),
 ((10596, 16068), 0.77778),
 ((10596, 16394), 0.77778),
 ((10889, 15759), 0.77778),
 ((10889, 16068), 0.77778),
 ((10889, 16394), 0.77778),
 ((11472, 15759), 0.77778),
 ((11472, 16068), 0.77778),
 ((11472, 16394), 0.77778),
 ((12351, 15759), 0.77778),
 ((12351, 16068), 0.77778),
 ((12351, 16394), 0.77778),
 ((13253, 15759), 0.77778),
 ((13253, 16068), 0.77778),
 ((13253, 16394), 0.77778),
 ((13601, 15759), 0.77778),
 ((13601, 16068), 0.77778),
 ((13601, 16394), 0.77778),
 ((14266, 15759), 0.77778),
 ((14266, 16068), 0.77778),
 ((14266, 16394), 0.77778),
 ((15232, 15759), 0.77778),
 ((15232, 16068), 0.77778),
 ((15232, 16394), 0.77778),
 ((7222, 16772), 0.76923),
 ((9248, 11896), 0.76471),
 ((10762, 11896), 0.76471),
 ((552, 565), 0.75),
 ((3489, 4620), 0.75),
 ((7170, 8113), 0.75),
 ((6429, 6431), 0.73333),
 ((6429, 6432), 0.73333),
 ((6429, 6433), 0.73333),
 ((6431, 6432), 0.73333),
 ((6431, 6433), 0.73333),
 ((6432, 6433), 0.73333),
 ((8880, 9730), 0.73333),
 ((8880, 10034), 0.73333),
 ((8880, 10947), 0.73333),
 ((9433, 10341), 0.73333),
 ((9433, 10638), 0.73333),
 ((9730, 10034), 0.73333),
 ((9730, 10947), 0.73333),
 ((10034, 10947), 0.73333),
 ((5868, 6843), 0.72727),
 ((5868, 7169), 0.72727),
 ((5868, 7464), 0.72727),
 ((5868, 7778), 0.72727),
 ((5950, 6843), 0.72727),
 ((5950, 7169), 0.72727),
 ((5950, 7464), 0.72727),
 ((5950, 7778), 0.72727),
 ((6013, 6843), 0.72727),
 ((6013, 7169), 0.72727),
 ((6013, 7464), 0.72727),
 ((6013, 7778), 0.72727),
 ((6081, 6843), 0.72727),
 ((6081, 7169), 0.72727),
 ((6081, 7464), 0.72727),
 ((6081, 7778), 0.72727),
 ((6189, 6843), 0.72727),
 ((6189, 7169), 0.72727),
 ((6189, 7464), 0.72727),
 ((6189, 7778), 0.72727),
 ((6261, 6843), 0.72727),
 ((6261, 7169), 0.72727),
 ((6261, 7464), 0.72727),
 ((6261, 7778), 0.72727),
 ((6322, 6843), 0.72727),
 ((6322, 7169), 0.72727),
 ((6322, 7464), 0.72727),
 ((6322, 7778), 0.72727),
 ((6388, 6843), 0.72727),
 ((6388, 7169), 0.72727),
 ((6388, 7464), 0.72727),
 ((6388, 7778), 0.72727),
 ((6562, 6843), 0.72727),
 ((6562, 7169), 0.72727),
 ((6562, 7464), 0.72727),
 ((6562, 7778), 0.72727),
 ((6639, 6843), 0.72727),
 ((6639, 7169), 0.72727),
 ((6639, 7464), 0.72727),
 ((6639, 7778), 0.72727),
 ((6684, 6843), 0.72727),
 ((6684, 7169), 0.72727),
 ((6684, 7464), 0.72727),
 ((6684, 7778), 0.72727),
 ((6764, 6843), 0.72727),
 ((6764, 7169), 0.72727),
 ((6764, 7464), 0.72727),
 ((6764, 7778), 0.72727),
 ((9248, 9558), 0.72222),
 ((9558, 10762), 0.72222),
 ((9852, 11896), 0.72222),
 ((11075, 11896), 0.72222),
 ((493, 494), 0.71429),
 ((493, 623), 0.71429),
 ((493, 624), 0.71429),
 ((493, 687), 0.71429),
 ((493, 688), 0.71429),
 ((493, 750), 0.71429),
 ((494, 623), 0.71429),
 ((494, 624), 0.71429),
 ((494, 687), 0.71429),
 ((494, 688), 0.71429),
 ((494, 750), 0.71429),
 ((623, 624), 0.71429),
 ((623, 687), 0.71429),
 ((623, 688), 0.71429),
 ((623, 750), 0.71429),
 ((624, 687), 0.71429),
 ((624, 688), 0.71429),
 ((624, 750), 0.71429),
 ((687, 688), 0.71429),
 ((687, 750), 0.71429),
 ((688, 750), 0.71429),
 ((9433, 11255), 0.71429),
 ((15964, 16411), 0.71429),
 ((9253, 11638), 0.7),
 ((11638, 14458), 0.7),
 ((11638, 15947), 0.7),
 ((10434, 12753), 0.69231),
 ((8880, 10341), 0.6875),
 ((8880, 10638), 0.6875),
 ((9730, 10341), 0.6875),
 ((9730, 10638), 0.6875),
 ((10034, 10341), 0.6875),
 ((10034, 10638), 0.6875),
 ((10341, 10947), 0.6875),
 ((10638, 10947), 0.6875),
 ((13630, 14213), 0.6875),
 ((9558, 9852), 0.68421),
 ((9558, 11075), 0.68421),
 ((3053, 3125), 0.68),
 ((682, 1661), 0.66667),
 ((682, 2218), 0.66667),
 ((682, 2568), 0.66667),
 ((924, 1661), 0.66667),
 ((924, 2218), 0.66667),
 ((924, 2568), 0.66667),
 ((2909, 11791), 0.66667),
 ((2909, 12233), 0.66667),
 ((2909, 12561), 0.66667),
 ((2909, 12845), 0.66667),
 ((2909, 13034), 0.66667),
 ((2909, 13411), 0.66667),
 ((2909, 13745), 0.66667),
 ((2909, 14002), 0.66667),
 ((2909, 14419), 0.66667),
 ((2909, 14755), 0.66667),
 ((2909, 15113), 0.66667),
 ((2909, 15839), 0.66667),
 ((2909, 16222), 0.66667),
 ((2909, 16472), 0.66667),
 ((3375, 11791), 0.66667),
 ((3375, 12233), 0.66667),
 ((3375, 12561), 0.66667),
 ((3375, 12845), 0.66667),
 ((3375, 13034), 0.66667),
 ((3375, 13411), 0.66667),
 ((3375, 13745), 0.66667),
 ((3375, 14002), 0.66667),
 ((3375, 14419), 0.66667),
 ((3375, 14755), 0.66667),
 ((3375, 15113), 0.66667),
 ((3375, 15839), 0.66667),
 ((3375, 16222), 0.66667),
 ((3375, 16472), 0.66667),
 ((3435, 4227), 0.66667),
 ((3864, 4936), 0.66667),
 ((3864, 5040), 0.66667),
 ((3864, 5099), 0.66667),
 ((3864, 5168), 0.66667),
 ((3864, 5242), 0.66667),
 ((3864, 5303), 0.66667),
 ((3864, 5404), 0.66667),
 ((3864, 5465), 0.66667),
 ((3864, 5542), 0.66667),
 ((3864, 5626), 0.66667),
 ((3864, 5696), 0.66667),
 ((3864, 5794), 0.66667),
 ((3864, 5852), 0.66667),
 ((3864, 5932), 0.66667),
 ((3864, 6000), 0.66667),
 ((3864, 6067), 0.66667),
 ((3864, 6171), 0.66667),
 ((3864, 6233), 0.66667),
 ((3864, 6303), 0.66667),
 ((3864, 6376), 0.66667),
 ((3864, 6548), 0.66667),
 ((3864, 6606), 0.66667),
 ((3864, 6680), 0.66667),
 ((3864, 6747), 0.66667),
 ((3864, 6814), 0.66667),
 ((3864, 6924), 0.66667),
 ((3864, 7193), 0.66667),
 ((3864, 7306), 0.66667),
 ((3864, 7371), 0.66667),
 ((3864, 7537), 0.66667),
 ((3864, 7611), 0.66667),
 ((3864, 7791), 0.66667),
 ((3864, 7824), 0.66667),
 ((3864, 7966), 0.66667),
 ((3864, 8023), 0.66667),
 ((3864, 8075), 0.66667),
 ((3864, 8123), 0.66667),
 ((3864, 8210), 0.66667),
 ((3864, 8285), 0.66667),
 ((3864, 8402), 0.66667),
 ((3864, 8564), 0.66667),
 ((3864, 8648), 0.66667),
 ((3864, 8994), 0.66667),
 ((3929, 4936), 0.66667),
 ((3929, 5040), 0.66667),
 ((3929, 5099), 0.66667),
 ((3929, 5168), 0.66667),
 ((3929, 5242), 0.66667),
 ((3929, 5303), 0.66667),
 ((3929, 5404), 0.66667),
 ((3929, 5465), 0.66667),
 ((3929, 5542), 0.66667),
 ((3929, 5626), 0.66667),
 ((3929, 5696), 0.66667),
 ((3929, 5794), 0.66667),
 ((3929, 5852), 0.66667),
 ((3929, 5932), 0.66667),
 ((3929, 6000), 0.66667),
 ((3929, 6067), 0.66667),
 ((3929, 6171), 0.66667),
 ((3929, 6233), 0.66667),
 ((3929, 6303), 0.66667),
 ((3929, 6376), 0.66667),
 ((3929, 6548), 0.66667),
 ((3929, 6606), 0.66667),
 ((3929, 6680), 0.66667),
 ((3929, 6747), 0.66667),
 ((3929, 6814), 0.66667),
 ((3929, 6924), 0.66667),
 ((3929, 7193), 0.66667),
 ((3929, 7306), 0.66667),
 ((3929, 7371), 0.66667),
 ((3929, 7537), 0.66667),
 ((3929, 7611), 0.66667),
 ((3929, 7791), 0.66667),
 ((3929, 7824), 0.66667),
 ((3929, 7966), 0.66667),
 ((3929, 8023), 0.66667),
 ((3929, 8075), 0.66667),
 ((3929, 8123), 0.66667),
 ((3929, 8210), 0.66667),
 ((3929, 8285), 0.66667),
 ((3929, 8402), 0.66667),
 ((3929, 8564), 0.66667),
 ((3929, 8648), 0.66667),
 ((3929, 8994), 0.66667),
 ((4008, 4936), 0.66667),
 ((4008, 5040), 0.66667),
 ((4008, 5099), 0.66667),
 ((4008, 5168), 0.66667),
 ((4008, 5242), 0.66667),
 ((4008, 5303), 0.66667),
 ((4008, 5404), 0.66667),
 ((4008, 5465), 0.66667),
 ((4008, 5542), 0.66667),
 ((4008, 5626), 0.66667),
 ((4008, 5696), 0.66667),
 ((4008, 5794), 0.66667),
 ((4008, 5852), 0.66667),
 ((4008, 5932), 0.66667),
 ((4008, 6000), 0.66667),
 ((4008, 6067), 0.66667),
 ((4008, 6171), 0.66667),
 ((4008, 6233), 0.66667),
 ((4008, 6303), 0.66667),
 ((4008, 6376), 0.66667),
 ((4008, 6548), 0.66667),
 ((4008, 6606), 0.66667),
 ((4008, 6680), 0.66667),
 ((4008, 6747), 0.66667),
 ((4008, 6814), 0.66667),
 ((4008, 6924), 0.66667),
 ((4008, 7193), 0.66667),
 ((4008, 7306), 0.66667),
 ((4008, 7371), 0.66667),
 ((4008, 7537), 0.66667),
 ((4008, 7611), 0.66667),
 ((4008, 7791), 0.66667),
 ((4008, 7824), 0.66667),
 ((4008, 7966), 0.66667),
 ((4008, 8023), 0.66667),
 ((4008, 8075), 0.66667),
 ((4008, 8123), 0.66667),
 ((4008, 8210), 0.66667),
 ((4008, 8285), 0.66667),
 ((4008, 8402), 0.66667),
 ((4008, 8564), 0.66667),
 ((4008, 8648), 0.66667),
 ((4008, 8994), 0.66667),
 ((4078, 4936), 0.66667),
 ((4078, 5040), 0.66667),
 ((4078, 5099), 0.66667),
 ((4078, 5168), 0.66667),
 ((4078, 5242), 0.66667),
 ((4078, 5303), 0.66667),
 ((4078, 5404), 0.66667),
 ((4078, 5465), 0.66667),
 ((4078, 5542), 0.66667),
 ((4078, 5626), 0.66667),
 ((4078, 5696), 0.66667),
 ((4078, 5794), 0.66667),
 ((4078, 5852), 0.66667),
 ((4078, 5932), 0.66667),
 ((4078, 6000), 0.66667),
 ((4078, 6067), 0.66667),
 ((4078, 6171), 0.66667),
 ((4078, 6233), 0.66667),
 ((4078, 6303), 0.66667),
 ((4078, 6376), 0.66667),
 ((4078, 6548), 0.66667),
 ((4078, 6606), 0.66667),
 ((4078, 6680), 0.66667),
 ((4078, 6747), 0.66667),
 ((4078, 6814), 0.66667),
 ((4078, 6924), 0.66667),
 ((4078, 7193), 0.66667),
 ((4078, 7306), 0.66667),
 ((4078, 7371), 0.66667),
 ((4078, 7537), 0.66667),
 ((4078, 7611), 0.66667),
 ((4078, 7791), 0.66667),
 ((4078, 7824), 0.66667),
 ((4078, 7966), 0.66667),
 ((4078, 8023), 0.66667),
 ((4078, 8075), 0.66667),
 ((4078, 8123), 0.66667),
 ((4078, 8210), 0.66667),
 ((4078, 8285), 0.66667),
 ((4078, 8402), 0.66667),
 ((4078, 8564), 0.66667),
 ((4078, 8648), 0.66667),
 ((4078, 8994), 0.66667),
 ((4152, 4936), 0.66667),
 ((4152, 5040), 0.66667),
 ((4152, 5099), 0.66667),
 ((4152, 5168), 0.66667),
 ((4152, 5242), 0.66667),
 ((4152, 5303), 0.66667),
 ((4152, 5404), 0.66667),
 ((4152, 5465), 0.66667),
 ((4152, 5542), 0.66667),
 ((4152, 5626), 0.66667),
 ((4152, 5696), 0.66667),
 ((4152, 5794), 0.66667),
 ((4152, 5852), 0.66667),
 ((4152, 5932), 0.66667),
 ((4152, 6000), 0.66667),
 ((4152, 6067), 0.66667),
 ((4152, 6171), 0.66667),
 ((4152, 6233), 0.66667),
 ((4152, 6303), 0.66667),
 ((4152, 6376), 0.66667),
 ((4152, 6548), 0.66667),
 ((4152, 6606), 0.66667),
 ((4152, 6680), 0.66667),
 ((4152, 6747), 0.66667),
 ((4152, 6814), 0.66667),
 ((4152, 6924), 0.66667),
 ((4152, 7193), 0.66667),
 ((4152, 7306), 0.66667),
 ((4152, 7371), 0.66667),
 ((4152, 7537), 0.66667),
 ((4152, 7611), 0.66667),
 ((4152, 7791), 0.66667),
 ((4152, 7824), 0.66667),
 ((4152, 7966), 0.66667),
 ((4152, 8023), 0.66667),
 ((4152, 8075), 0.66667),
 ((4152, 8123), 0.66667),
 ((4152, 8210), 0.66667),
 ((4152, 8285), 0.66667),
 ((4152, 8402), 0.66667),
 ((4152, 8564), 0.66667),
 ((4152, 8648), 0.66667),
 ((4152, 8994), 0.66667),
 ((4260, 4936), 0.66667),
 ((4260, 5040), 0.66667),
 ((4260, 5099), 0.66667),
 ((4260, 5168), 0.66667),
 ((4260, 5242), 0.66667),
 ((4260, 5303), 0.66667),
 ((4260, 5404), 0.66667),
 ((4260, 5465), 0.66667),
 ((4260, 5542), 0.66667),
 ((4260, 5626), 0.66667),
 ((4260, 5696), 0.66667),
 ((4260, 5794), 0.66667),
 ((4260, 5852), 0.66667),
 ((4260, 5932), 0.66667),
 ((4260, 6000), 0.66667),
 ((4260, 6067), 0.66667),
 ((4260, 6171), 0.66667),
 ((4260, 6233), 0.66667),
 ((4260, 6303), 0.66667),
 ((4260, 6376), 0.66667),
 ((4260, 6548), 0.66667),
 ((4260, 6606), 0.66667),
 ((4260, 6680), 0.66667),
 ((4260, 6747), 0.66667),
 ((4260, 6814), 0.66667),
 ((4260, 6924), 0.66667),
 ((4260, 7193), 0.66667),
 ((4260, 7306), 0.66667),
 ((4260, 7371), 0.66667),
 ((4260, 7537), 0.66667),
 ((4260, 7611), 0.66667),
 ((4260, 7791), 0.66667),
 ((4260, 7824), 0.66667),
 ((4260, 7966), 0.66667),
 ((4260, 8023), 0.66667),
 ((4260, 8075), 0.66667),
 ((4260, 8123), 0.66667),
 ((4260, 8210), 0.66667),
 ((4260, 8285), 0.66667),
 ((4260, 8402), 0.66667),
 ((4260, 8564), 0.66667),
 ((4260, 8648), 0.66667),
 ((4260, 8994), 0.66667),
 ((4331, 4936), 0.66667),
 ((4331, 5040), 0.66667),
 ((4331, 5099), 0.66667),
 ((4331, 5168), 0.66667),
 ((4331, 5242), 0.66667),
 ((4331, 5303), 0.66667),
 ((4331, 5404), 0.66667),
 ((4331, 5465), 0.66667),
 ((4331, 5542), 0.66667),
 ((4331, 5626), 0.66667),
 ((4331, 5696), 0.66667),
 ((4331, 5794), 0.66667),
 ((4331, 5852), 0.66667),
 ((4331, 5932), 0.66667),
 ((4331, 6000), 0.66667),
 ((4331, 6067), 0.66667),
 ((4331, 6171), 0.66667),
 ((4331, 6233), 0.66667),
 ((4331, 6303), 0.66667),
 ((4331, 6376), 0.66667),
 ((4331, 6548), 0.66667),
 ((4331, 6606), 0.66667),
 ((4331, 6680), 0.66667),
 ((4331, 6747), 0.66667),
 ((4331, 6814), 0.66667),
 ((4331, 6924), 0.66667),
 ((4331, 7193), 0.66667),
 ((4331, 7306), 0.66667),
 ((4331, 7371), 0.66667),
 ((4331, 7537), 0.66667),
 ((4331, 7611), 0.66667),
 ((4331, 7791), 0.66667),
 ((4331, 7824), 0.66667),
 ((4331, 7966), 0.66667),
 ((4331, 8023), 0.66667),
 ((4331, 8075), 0.66667),
 ((4331, 8123), 0.66667),
 ((4331, 8210), 0.66667),
 ((4331, 8285), 0.66667),
 ((4331, 8402), 0.66667),
 ((4331, 8564), 0.66667),
 ((4331, 8648), 0.66667),
 ((4331, 8994), 0.66667),
 ((4403, 4936), 0.66667),
 ((4403, 5040), 0.66667),
 ((4403, 5099), 0.66667),
 ((4403, 5168), 0.66667),
 ((4403, 5242), 0.66667),
 ((4403, 5303), 0.66667),
 ((4403, 5404), 0.66667),
 ((4403, 5465), 0.66667),
 ((4403, 5542), 0.66667),
 ((4403, 5626), 0.66667),
 ((4403, 5696), 0.66667),
 ((4403, 5794), 0.66667),
 ((4403, 5852), 0.66667),
 ((4403, 5932), 0.66667),
 ((4403, 6000), 0.66667),
 ((4403, 6067), 0.66667),
 ((4403, 6171), 0.66667),
 ((4403, 6233), 0.66667),
 ((4403, 6303), 0.66667),
 ((4403, 6376), 0.66667),
 ((4403, 6548), 0.66667),
 ((4403, 6606), 0.66667),
 ((4403, 6680), 0.66667),
 ((4403, 6747), 0.66667),
 ((4403, 6814), 0.66667),
 ((4403, 6924), 0.66667),
 ((4403, 7193), 0.66667),
 ((4403, 7306), 0.66667),
 ((4403, 7371), 0.66667),
 ((4403, 7537), 0.66667),
 ((4403, 7611), 0.66667),
 ((4403, 7791), 0.66667),
 ((4403, 7824), 0.66667),
 ((4403, 7966), 0.66667),
 ((4403, 8023), 0.66667),
 ((4403, 8075), 0.66667),
 ((4403, 8123), 0.66667),
 ((4403, 8210), 0.66667),
 ((4403, 8285), 0.66667),
 ((4403, 8402), 0.66667),
 ((4403, 8564), 0.66667),
 ((4403, 8648), 0.66667),
 ((4403, 8994), 0.66667),
 ((4484, 4936), 0.66667),
 ((4484, 5040), 0.66667),
 ((4484, 5099), 0.66667),
 ((4484, 5168), 0.66667),
 ((4484, 5242), 0.66667),
 ((4484, 5303), 0.66667),
 ((4484, 5404), 0.66667),
 ((4484, 5465), 0.66667),
 ((4484, 5542), 0.66667),
 ((4484, 5626), 0.66667),
 ((4484, 5696), 0.66667),
 ((4484, 5794), 0.66667),
 ((4484, 5852), 0.66667),
 ((4484, 5932), 0.66667),
 ((4484, 6000), 0.66667),
 ((4484, 6067), 0.66667),
 ((4484, 6171), 0.66667),
 ((4484, 6233), 0.66667),
 ((4484, 6303), 0.66667),
 ((4484, 6376), 0.66667),
 ((4484, 6548), 0.66667),
 ((4484, 6606), 0.66667),
 ((4484, 6680), 0.66667),
 ((4484, 6747), 0.66667),
 ((4484, 6814), 0.66667),
 ((4484, 6924), 0.66667),
 ((4484, 7193), 0.66667),
 ((4484, 7306), 0.66667),
 ((4484, 7371), 0.66667),
 ((4484, 7537), 0.66667),
 ((4484, 7611), 0.66667),
 ((4484, 7791), 0.66667),
 ((4484, 7824), 0.66667),
 ((4484, 7966), 0.66667),
 ((4484, 8023), 0.66667),
 ((4484, 8075), 0.66667),
 ((4484, 8123), 0.66667),
 ((4484, 8210), 0.66667),
 ((4484, 8285), 0.66667),
 ((4484, 8402), 0.66667),
 ((4484, 8564), 0.66667),
 ((4484, 8648), 0.66667),
 ((4484, 8994), 0.66667),
 ((4565, 4936), 0.66667),
 ((4565, 5040), 0.66667),
 ((4565, 5099), 0.66667),
 ((4565, 5168), 0.66667),
 ((4565, 5242), 0.66667),
 ((4565, 5303), 0.66667),
 ((4565, 5404), 0.66667),
 ((4565, 5465), 0.66667),
 ((4565, 5542), 0.66667),
 ((4565, 5626), 0.66667),
 ((4565, 5696), 0.66667),
 ((4565, 5794), 0.66667),
 ((4565, 5852), 0.66667),
 ((4565, 5932), 0.66667),
 ((4565, 6000), 0.66667),
 ((4565, 6067), 0.66667),
 ((4565, 6171), 0.66667),
 ((4565, 6233), 0.66667),
 ((4565, 6303), 0.66667),
 ((4565, 6376), 0.66667),
 ((4565, 6548), 0.66667),
 ((4565, 6606), 0.66667),
 ((4565, 6680), 0.66667),
 ((4565, 6747), 0.66667),
 ((4565, 6814), 0.66667),
 ((4565, 6924), 0.66667),
 ((4565, 7193), 0.66667),
 ((4565, 7306), 0.66667),
 ((4565, 7371), 0.66667),
 ((4565, 7537), 0.66667),
 ((4565, 7611), 0.66667),

In [ ]:
print(abstract.abstract.iloc[552])
print(abstract.abstract.iloc[565])

Senator Booker interviews for The New York Times’s endorsement.
Senator Warren interviews for The New York Times’s endorsement.

MinHash

In [74]:
from datasketch import MinHash, MinHashLSH

In [78]:
def create_minhash(tokens, num_permitations=128):
    minhash = MinHash(num_perm=num_permitations, seed=7)
    for token in tokens:
        minhash.update(token.encode('utf8'))
    return minhash

In [79]:
def generate_minhashs(tokens_list):
    minhashs = {}
    for idx, tokens in enumerate(tokens_list):
        minhash_t = create_minhash(tokens)
        minhashs[idx] = minhash_t
    return minhashs

In [80]:
minhashs_list = generate_minhashs(abstract.processed)

In [82]:
minhashs_list[0].hashvalues

array([ 707749404,  347028220,  400058551,   43546765,  505129740,
         15608448,  627940067,  128669491,  289958203,  774278953,
        152749646, 1166465831,  373291504,  389376052,  711524712,
         91162290,   75188705,   99206128,  243382014,  574589508,
        165060821,  480936439,   70625004, 1311977962,  611409358,
        459536849,  297682872,  147104448,  261698346,  315374390,
        372653730,    8865041,  494367057,  292406418,  577674347,
        480146619,  470874541,  643573593,   53452095,    7994244,
         77760892,   59969147,   18083807, 1018128814,  133494663,
        117388653,  229115136,  492263217,   99627946,  664683497,
        700143525,  441361013,  117021468,  418212819,  313193937,
        984593224,  136077265,    1841052,  183609486,  205513169,
         47339689,  291663679,  271958937,  312033872,  183772422,
       1222222728,  432939470,   88571120,   62543956,  490202235,
        755905331,  167218994,  332961802,  133777597,  436702582,
        183587862,   47755949,  655435780,  141690574,  332458632,
       1057072105,  944812111,  429371917,   91342679,   80390590,
        311018743,  227940614,  849178365,  566456650,  632004684,
         36417451,  972950336,  260170860,  808250304,   48276091,
        756564384,   60029901,  144298249,  229405610,  393244700,
        114242774,  276586977,  182085835,   21921614,  562181499,
       1208602793,  140587653, 1322620920,  464649112,  276789232,
        146078520,  250401064,   84822986,  844872823, 1499523981,
       1065495523,   20818135, 1598059318,  262822945,  309215501,
        315278772,  839649788,  607711903,  184455361,   38076555,
        337994250,   40912569,   43909692], dtype=uint64)

In [88]:
def minhash_sim_for_main (minhash_list, number_main:int, top_k=5):
    main_minhash = minhash_list[number_main]
    overall_minhash_for_main = dict()
    for idxr, minhash in enumerate(minhash_list):
        print(main_minhash)
        print(minhash)
        print(idxr)
        minhash_sim = main_minhash.jaccard(minhash)
        overall_minhash_for_main[idxr] = minhash_sim

    overall_minhash_for_main = sorted(
    overall_minhash_for_main.items(),
    key=lambda x: x[1],
    reverse=True
    )[:top_k]
    return overall_minhash_for_main

In [98]:
def minhash_sim_for_main (minhash_list, number_main:int, top_k=5):
    main_minhash = minhash_list[number_main]
    overall_minhash_for_main = dict()
    for i in range(len(minhash_list)):
        if i == number_main:
            continue
        minhash = minhash_list[i]
        minhash_sim = main_minhash.jaccard(minhash)
        overall_minhash_for_main[i] = minhash_sim

    overall_minhash_for_main = sorted(
    overall_minhash_for_main.items(),
    key=lambda x: x[1],
    reverse=True
    )[:top_k]
    return overall_minhash_for_main

Checking minhash similarity for random articles

In [99]:
minhash_check = minhash_sim_for_main(minhashs_list, 10)

In [100]:
minhash_check

[(2952, 0.203125),
 (2526, 0.1328125),
 (10532, 0.1328125),
 (12416, 0.1171875),
 (2988, 0.109375)]

In [97]:
abstract.processed.iloc[[10, 2952, 2526]].values

array([{'eat', 'step', 'intermittent', 'less', 'try', 'fasting', 'drink', 'oyster', 'alcohol'},
       {'balanced', 'designer', 'intermittent', 'yam', 'proponent', 'fasting', 'soup', 'rely', 'bright', 'drink', 'stay', 'herbal', 'simple'},
       {'try', 'easy'}], dtype=object)

Results are correct.

The next step is creating pairs of comparison between each article's minhash and every other minhash.

In [106]:
from tqdm import tqdm

In [104]:
!pip install tqdm

Requirement already satisfied: tqdm in c:\users\mi\anaconda3\lib\site-packages (4.66.4)
Requirement already satisfied: colorama in c:\users\mi\anaconda3\lib\site-packages (from tqdm) (0.4.6)

In [107]:
def minhash_total(minhash_list, threshold = 0.2):
    minhash_final = {}
    for i in tqdm(range(len(minhash_list))):
        minhash_sim_idx = minhash_sim_for_main(minhash_list, i, top_k=len(minhash_list))
        for pairs in minhash_sim_idx:
            if (pairs[1] > threshold) and (pairs[1] < 1) and (pairs[0] > i):
                minhash_final[(i, pairs[0])] = pairs[1]

    total_minhash = sorted(
    minhash_final.items(),
    key=lambda x: x[1],
    reverse=True
    )
    return total_minhash

In [108]:
minhashtotal_check = minhash_total(minhashs_list)

  0%|          | 0/16787 [00:00<?, ?it/s]

100%|██████████| 16787/16787 [13:02<00:00, 21.45it/s]

In [109]:
minhashtotal_check

[((9248, 9852), 0.9375),
 ((9248, 11075), 0.9375),
 ((9852, 10762), 0.9375),
 ((10762, 11075), 0.9375),
 ((58, 9253), 0.9296875),
 ((3015, 9253), 0.9296875),
 ((4533, 9253), 0.9296875),
 ((7804, 9253), 0.9296875),
 ((5724, 16679), 0.90625),
 ((8144, 8446), 0.90625),
 ((58, 14458), 0.890625),
 ((58, 15947), 0.890625),
 ((3015, 14458), 0.890625),
 ((3015, 15947), 0.890625),
 ((4533, 14458), 0.890625),
 ((4533, 15947), 0.890625),
 ((7804, 14458), 0.890625),
 ((7804, 15947), 0.890625),
 ((8731, 10202), 0.8828125),
 ((8731, 10510), 0.8828125),
 ((8731, 10807), 0.8828125),
 ((9015, 10202), 0.8828125),
 ((9015, 10510), 0.8828125),
 ((9015, 10807), 0.8828125),
 ((9295, 10202), 0.8828125),
 ((9295, 10510), 0.8828125),
 ((9295, 10807), 0.8828125),
 ((9598, 10202), 0.8828125),
 ((9598, 10510), 0.8828125),
 ((9598, 10807), 0.8828125),
 ((9900, 10202), 0.8828125),
 ((9900, 10510), 0.8828125),
 ((9900, 10807), 0.8828125),
 ((387, 12219), 0.875),
 ((726, 12219), 0.875),
 ((1028, 12219), 0.875),
 ((2067, 12219), 0.875),
 ((2334, 12219), 0.875),
 ((2666, 12219), 0.875),
 ((3362, 12219), 0.875),
 ((3759, 12219), 0.875),
 ((4133, 12219), 0.875),
 ((4537, 12219), 0.875),
 ((4923, 12219), 0.875),
 ((5294, 12219), 0.875),
 ((5686, 12219), 0.875),
 ((6056, 12219), 0.875),
 ((6424, 12219), 0.875),
 ((6801, 12219), 0.875),
 ((7178, 12219), 0.875),
 ((7501, 12219), 0.875),
 ((8446, 8731), 0.875),
 ((8446, 9015), 0.875),
 ((8446, 9295), 0.875),
 ((8446, 9598), 0.875),
 ((8446, 9900), 0.875),
 ((12219, 12542), 0.875),
 ((12219, 12840), 0.875),
 ((12219, 13141), 0.875),
 ((12219, 13449), 0.875),
 ((12219, 13784), 0.875),
 ((12219, 14454), 0.875),
 ((12219, 14784), 0.875),
 ((12219, 15099), 0.875),
 ((12219, 15628), 0.875),
 ((12219, 15945), 0.875),
 ((8144, 10202), 0.859375),
 ((8144, 10510), 0.859375),
 ((8144, 10807), 0.859375),
 ((406, 15964), 0.828125),
 ((4333, 4514), 0.828125),
 ((4807, 15964), 0.828125),
 ((8365, 8367), 0.828125),
 ((9253, 14458), 0.828125),
 ((9253, 15947), 0.828125),
 ((12582, 12689), 0.828125),
 ((12975, 15964), 0.828125),
 ((6712, 8960), 0.8125),
 ((11796, 11988), 0.8125),
 ((5457, 12715), 0.8046875),
 ((6843, 7169), 0.8046875),
 ((6843, 7464), 0.8046875),
 ((6843, 7778), 0.8046875),
 ((8364, 8367), 0.8046875),
 ((9433, 9730), 0.8046875),
 ((16007, 16058), 0.8046875),
 ((623, 687), 0.796875),
 ((5545, 6071), 0.796875),
 ((5545, 7372), 0.796875),
 ((8364, 8365), 0.796875),
 ((8880, 9433), 0.796875),
 ((8368, 8370), 0.7890625),
 ((530, 15759), 0.78125),
 ((530, 16068), 0.78125),
 ((530, 16394), 0.78125),
 ((1855, 15759), 0.78125),
 ((1855, 16068), 0.78125),
 ((1855, 16394), 0.78125),
 ((2822, 15759), 0.78125),
 ((2822, 16068), 0.78125),
 ((2822, 16394), 0.78125),
 ((3146, 15759), 0.78125),
 ((3146, 16068), 0.78125),
 ((3146, 16394), 0.78125),
 ((3511, 15759), 0.78125),
 ((3511, 16068), 0.78125),
 ((3511, 16394), 0.78125),
 ((3893, 15759), 0.78125),
 ((3893, 16068), 0.78125),
 ((3893, 16394), 0.78125),
 ((4227, 5007), 0.78125),
 ((5828, 15759), 0.78125),
 ((5828, 16068), 0.78125),
 ((5828, 16394), 0.78125),
 ((6207, 15759), 0.78125),
 ((6207, 16068), 0.78125),
 ((6207, 16394), 0.78125),
 ((7222, 16772), 0.78125),
 ((7915, 15759), 0.78125),
 ((7915, 16068), 0.78125),
 ((7915, 16394), 0.78125),
 ((8144, 8731), 0.78125),
 ((8144, 9015), 0.78125),
 ((8144, 9295), 0.78125),
 ((8144, 9598), 0.78125),
 ((8144, 9900), 0.78125),
 ((8360, 8367), 0.78125),
 ((8446, 10202), 0.78125),
 ((8446, 10510), 0.78125),
 ((8446, 10807), 0.78125),
 ((8526, 15759), 0.78125),
 ((8526, 16068), 0.78125),
 ((8526, 16394), 0.78125),
 ((9096, 15759), 0.78125),
 ((9096, 16068), 0.78125),
 ((9096, 16394), 0.78125),
 ((9380, 15759), 0.78125),
 ((9380, 16068), 0.78125),
 ((9380, 16394), 0.78125),
 ((9433, 10034), 0.78125),
 ((9433, 10947), 0.78125),
 ((10355, 15759), 0.78125),
 ((10355, 16068), 0.78125),
 ((10355, 16394), 0.78125),
 ((10434, 12753), 0.78125),
 ((10596, 15759), 0.78125),
 ((10596, 16068), 0.78125),
 ((10596, 16394), 0.78125),
 ((10889, 15759), 0.78125),
 ((10889, 16068), 0.78125),
 ((10889, 16394), 0.78125),
 ((11472, 15759), 0.78125),
 ((11472, 16068), 0.78125),
 ((11472, 16394), 0.78125),
 ((12351, 15759), 0.78125),
 ((12351, 16068), 0.78125),
 ((12351, 16394), 0.78125),
 ((13253, 15759), 0.78125),
 ((13253, 16068), 0.78125),
 ((13253, 16394), 0.78125),
 ((13601, 15759), 0.78125),
 ((13601, 16068), 0.78125),
 ((13601, 16394), 0.78125),
 ((14266, 15759), 0.78125),
 ((14266, 16068), 0.78125),
 ((14266, 16394), 0.78125),
 ((15232, 15759), 0.78125),
 ((15232, 16068), 0.78125),
 ((15232, 16394), 0.78125),
 ((88, 173), 0.7734375),
 ((406, 16411), 0.7734375),
 ((624, 687), 0.7734375),
 ((3489, 4620), 0.7734375),
 ((4807, 16411), 0.7734375),
 ((7170, 8113), 0.7734375),
 ((8360, 8364), 0.7734375),
 ((8360, 8365), 0.7734375),
 ((8361, 8364), 0.7734375),
 ((8362, 8365), 0.7734375),
 ((8368, 8369), 0.7734375),
 ((12975, 16411), 0.7734375),
 ((493, 687), 0.765625),
 ((6429, 6430), 0.765625),
 ((8361, 8365), 0.765625),
 ((8366, 8367), 0.765625),
 ((8369, 8370), 0.765625),
 ((13371, 13868), 0.765625),
 ((624, 750), 0.7578125),
 ((687, 688), 0.7578125),
 ((687, 750), 0.7578125),
 ((8359, 8367), 0.7578125),
 ((8361, 8367), 0.7578125),
 ((8362, 8364), 0.7578125),
 ((8362, 8367), 0.7578125),
 ((9248, 11896), 0.7578125),
 ((10762, 11896), 0.7578125),
 ((493, 624), 0.75),
 ((552, 565), 0.75),
 ((8359, 8365), 0.75),
 ((8365, 8366), 0.75),
 ((9433, 10638), 0.75),
 ((623, 624), 0.7421875),
 ((624, 688), 0.734375),
 ((5166, 9456), 0.734375),
 ((6430, 6432), 0.734375),
 ((8880, 10034), 0.734375),
 ((9248, 9558), 0.734375),
 ((9558, 10762), 0.734375),
 ((494, 624), 0.7265625),
 ((494, 687), 0.7265625),
 ((623, 688), 0.7265625),
 ((6429, 6432), 0.7265625),
 ((8359, 8364), 0.7265625),
 ((8360, 8361), 0.7265625),
 ((8360, 8362), 0.7265625),
 ((8364, 8366), 0.7265625),
 ((8880, 10947), 0.7265625),
 ((9433, 11255), 0.7265625),
 ((9852, 11896), 0.7265625),
 ((11075, 11896), 0.7265625),
 ((493, 623), 0.71875),
 ((493, 688), 0.71875),
 ((623, 750), 0.71875),
 ((688, 750), 0.71875),
 ((8880, 9730), 0.71875),
 ((9433, 10341), 0.71875),
 ((6430, 6431), 0.7109375),
 ((8360, 8366), 0.7109375),
 ((8361, 8362), 0.7109375),
 ((8362, 8366), 0.7109375),
 ((9730, 10947), 0.7109375),
 ((10034, 10947), 0.7109375),
 ((493, 750), 0.703125),
 ((6429, 6431), 0.703125),
 ((8359, 8362), 0.703125),
 ((8359, 8366), 0.703125),
 ((8361, 8366), 0.703125),
 ((9558, 9852), 0.703125),
 ((9558, 11075), 0.703125),
 ((9730, 10034), 0.703125),
 ((552, 624), 0.6953125),
 ((6429, 6433), 0.6953125),
 ((8359, 8360), 0.6953125),
 ((8359, 8361), 0.6953125),
 ((58, 11638), 0.6875),
 ((494, 623), 0.6875),
 ((494, 750), 0.6875),
 ((552, 687), 0.6875),
 ((3015, 11638), 0.6875),
 ((4533, 11638), 0.6875),
 ((7804, 11638), 0.6875),
 ((10034, 10341), 0.6875),
 ((493, 494), 0.6796875),
 ((494, 688), 0.6796875),
 ((10034, 10638), 0.6796875),
 ((10638, 10947), 0.6796875),
 ((493, 552), 0.671875),
 ((552, 623), 0.671875),
 ((6430, 6433), 0.671875),
 ((8880, 11255), 0.671875),
 ((9730, 11255), 0.671875),
 ((15836, 16409), 0.671875),
 ((552, 750), 0.6640625),
 ((565, 687), 0.6640625),
 ((5166, 16409), 0.6640625),
 ((5673, 7170), 0.6640625),
 ((6432, 6433), 0.6640625),
 ((9456, 16409), 0.6640625),
 ((9730, 10638), 0.6640625),
 ((10034, 11255), 0.6640625),
 ((10341, 10947), 0.6640625),
 ((11368, 14550), 0.6640625),
 ((565, 623), 0.65625),
 ((2909, 11791), 0.65625),
 ((2909, 12233), 0.65625),
 ((2909, 12561), 0.65625),
 ((2909, 12845), 0.65625),
 ((2909, 13034), 0.65625),
 ((2909, 13411), 0.65625),
 ((2909, 13745), 0.65625),
 ((2909, 14002), 0.65625),
 ((2909, 14419), 0.65625),
 ((2909, 14755), 0.65625),
 ((2909, 15113), 0.65625),
 ((2909, 15839), 0.65625),
 ((2909, 16222), 0.65625),
 ((2909, 16472), 0.65625),
 ((3375, 11791), 0.65625),
 ((3375, 12233), 0.65625),
 ((3375, 12561), 0.65625),
 ((3375, 12845), 0.65625),
 ((3375, 13034), 0.65625),
 ((3375, 13411), 0.65625),
 ((3375, 13745), 0.65625),
 ((3375, 14002), 0.65625),
 ((3375, 14419), 0.65625),
 ((3375, 14755), 0.65625),
 ((3375, 15113), 0.65625),
 ((3375, 15839), 0.65625),
 ((3375, 16222), 0.65625),
 ((3375, 16472), 0.65625),
 ((4875, 11791), 0.65625),
 ((4875, 12233), 0.65625),
 ((4875, 12561), 0.65625),
 ((4875, 12845), 0.65625),
 ((4875, 13034), 0.65625),
 ((4875, 13411), 0.65625),
 ((4875, 13745), 0.65625),
 ((4875, 14002), 0.65625),
 ((4875, 14419), 0.65625),
 ((4875, 14755), 0.65625),
 ((4875, 15113), 0.65625),
 ((4875, 15839), 0.65625),
 ((4875, 16222), 0.65625),
 ((4875, 16472), 0.65625),
 ((5304, 11791), 0.65625),
 ((5304, 12233), 0.65625),
 ((5304, 12561), 0.65625),
 ((5304, 12845), 0.65625),
 ((5304, 13034), 0.65625),
 ((5304, 13411), 0.65625),
 ((5304, 13745), 0.65625),
 ((5304, 14002), 0.65625),
 ((5304, 14419), 0.65625),
 ((5304, 14755), 0.65625),
 ((5304, 15113), 0.65625),
 ((5304, 15839), 0.65625),
 ((5304, 16222), 0.65625),
 ((5304, 16472), 0.65625),
 ((5868, 7169), 0.65625),
 ((5868, 7464), 0.65625),
 ((5868, 7778), 0.65625),
 ((5950, 7169), 0.65625),
 ((5950, 7464), 0.65625),
 ((5950, 7778), 0.65625),
 ((6013, 7169), 0.65625),
 ((6013, 7464), 0.65625),
 ((6013, 7778), 0.65625),
 ((6081, 7169), 0.65625),
 ((6081, 7464), 0.65625),
 ((6081, 7778), 0.65625),
 ((6189, 7169), 0.65625),
 ((6189, 7464), 0.65625),
 ((6189, 7778), 0.65625),
 ((6261, 7169), 0.65625),
 ((6261, 7464), 0.65625),
 ((6261, 7778), 0.65625),
 ((6322, 7169), 0.65625),
 ((6322, 7464), 0.65625),
 ((6322, 7778), 0.65625),
 ((6388, 7169), 0.65625),
 ((6388, 7464), 0.65625),
 ((6388, 7778), 0.65625),
 ((6431, 6433), 0.65625),
 ((6562, 7169), 0.65625),
 ((6562, 7464), 0.65625),
 ((6562, 7778), 0.65625),
 ((6639, 7169), 0.65625),
 ((6639, 7464), 0.65625),
 ((6639, 7778), 0.65625),
 ((6684, 7169), 0.65625),
 ((6684, 7464), 0.65625),
 ((6684, 7778), 0.65625),
 ((6764, 7169), 0.65625),
 ((6764, 7464), 0.65625),
 ((6764, 7778), 0.65625),
 ((7194, 11791), 0.65625),
 ((7194, 12233), 0.65625),
 ((7194, 12561), 0.65625),
 ((7194, 12845), 0.65625),
 ((7194, 13034), 0.65625),
 ((7194, 13411), 0.65625),
 ((7194, 13745), 0.65625),
 ((7194, 14002), 0.65625),
 ((7194, 14419), 0.65625),
 ((7194, 14755), 0.65625),
 ((7194, 15113), 0.65625),
 ((7194, 15839), 0.65625),
 ((7194, 16222), 0.65625),
 ((7194, 16472), 0.65625),
 ((8880, 10341), 0.65625),
 ((9730, 10341), 0.65625),
 ((13630, 14213), 0.65625),
 ((77, 4335), 0.6484375),
 ((552, 688), 0.6484375),
 ((565, 688), 0.6484375),
 ((565, 750), 0.6484375),
 ((3053, 3125), 0.6484375),
 ((6198, 9482), 0.6484375),
 ((6431, 6432), 0.6484375),
 ((8880, 10638), 0.6484375),
 ((9253, 11638), 0.6484375),
 ((15964, 16411), 0.6484375),
 ((494, 552), 0.640625),
 ((565, 624), 0.640625),
 ((5868, 6843), 0.640625),
 ((5950, 6843), 0.640625),
 ((6013, 6843), 0.640625),
 ((6081, 6843), 0.640625),
 ((6189, 6843), 0.640625),
 ((6261, 6843), 0.640625),
 ((6322, 6843), 0.640625),
 ((6388, 6843), 0.640625),
 ((6562, 6843), 0.640625),
 ((6639, 6843), 0.640625),
 ((6684, 6843), 0.640625),
 ((6764, 6843), 0.640625),
 ((10947, 11255), 0.640625),
 ((493, 565), 0.6328125),
 ((985, 12169), 0.6328125),
 ((5693, 11994), 0.6328125),
 ((8367, 8368), 0.6328125),
 ((12169, 12432), 0.6328125),
 ((742, 15049), 0.625),
 ((8367, 8370), 0.625),
 ((8645, 14304), 0.625),
 ((12169, 14359), 0.625),
 ((12432, 15049), 0.625),
 ((494, 565), 0.6171875),
 ((682, 1661), 0.6171875),
 ((682, 2218), 0.6171875),
 ((682, 2568), 0.6171875),
 ((924, 1661), 0.6171875),
 ((924, 2218), 0.6171875),
 ((924, 2568), 0.6171875),
 ((985, 12432), 0.6171875),
 ((985, 15049), 0.6171875),
 ((2247, 15019), 0.6171875),
 ((5198, 15019), 0.6171875),
 ((8364, 8368), 0.6171875),
 ((8365, 8368), 0.6171875),
 ((10341, 11255), 0.6171875),
 ((12169, 15049), 0.6171875),
 ((13407, 15049), 0.6171875),
 ((742, 985), 0.609375),
 ((985, 1473), 0.609375),
 ((985, 13407), 0.609375),
 ((985, 14359), 0.609375),
 ((1791, 16335), 0.609375),
 ((2247, 3650), 0.609375),
 ((5096, 12432), 0.609375),
 ((8361, 8370), 0.609375),
 ((8364, 8370), 0.609375),
 ((8365, 8370), 0.609375),
 ((9558, 11896), 0.609375),
 ((10341, 10638), 0.609375),
 ((10638, 11255), 0.609375),
 ((11148, 16335), 0.609375),
 ((11638, 14458), 0.609375),
 ((11638, 15947), 0.609375),
 ((12169, 13407), 0.609375),
 ((12432, 13407), 0.609375),
 ((12432, 14068), 0.609375),
 ((12432, 14359), 0.609375),
 ((985, 9166), 0.6015625),
 ((1013, 16528), 0.6015625),
 ((1473, 12169), 0.6015625),
 ((1473, 12432), 0.6015625),
 ((1473, 15049), 0.6015625),
 ((2247, 8336), 0.6015625),
 ((3864, 4936), 0.6015625),
 ((3864, 5040), 0.6015625),
 ((3864, 5099), 0.6015625),
 ((3864, 5168), 0.6015625),
 ((3864, 5242), 0.6015625),
 ((3864, 5303), 0.6015625),
 ((3864, 5404), 0.6015625),
 ((3864, 5465), 0.6015625),
 ((3864, 5542), 0.6015625),
 ((3864, 5626), 0.6015625),
 ((3864, 5696), 0.6015625),
 ((3864, 5794), 0.6015625),
 ((3864, 5852), 0.6015625),
 ((3864, 5932), 0.6015625),
 ((3864, 6000), 0.6015625),
 ((3864, 6067), 0.6015625),
 ((3864, 6171), 0.6015625),
 ((3864, 6233), 0.6015625),
 ((3864, 6303), 0.6015625),
 ((3864, 6376), 0.6015625),
 ((3864, 6548), 0.6015625),
 ((3864, 6606), 0.6015625),
 ((3864, 6680), 0.6015625),
 ((3864, 6747), 0.6015625),
 ((3864, 6814), 0.6015625),
 ((3864, 6924), 0.6015625),
 ((3864, 7193), 0.6015625),
 ((3864, 7306), 0.6015625),
 ((3864, 7371), 0.6015625),
 ((3864, 7537), 0.6015625),
 ((3864, 7611), 0.6015625),
 ((3864, 7791), 0.6015625),
 ((3864, 7824), 0.6015625),
 ((3864, 7966), 0.6015625),
 ((3864, 8023), 0.6015625),
 ((3864, 8075), 0.6015625),
 ((3864, 8123), 0.6015625),
 ((3864, 8210), 0.6015625),
 ((3864, 8285), 0.6015625),
 ((3864, 8402), 0.6015625),
 ((3864, 8564), 0.6015625),
 ((3864, 8648), 0.6015625),
 ((3864, 8994), 0.6015625),
 ((3929, 4936), 0.6015625),
 ((3929, 5040), 0.6015625),
 ((3929, 5099), 0.6015625),
 ((3929, 5168), 0.6015625),
 ((3929, 5242), 0.6015625),
 ((3929, 5303), 0.6015625),
 ((3929, 5404), 0.6015625),
 ((3929, 5465), 0.6015625),
 ((3929, 5542), 0.6015625),
 ((3929, 5626), 0.6015625),
 ((3929, 5696), 0.6015625),
 ((3929, 5794), 0.6015625),
 ((3929, 5852), 0.6015625),
 ((3929, 5932), 0.6015625),
 ((3929, 6000), 0.6015625),
 ((3929, 6067), 0.6015625),
 ((3929, 6171), 0.6015625),
 ((3929, 6233), 0.6015625),
 ((3929, 6303), 0.6015625),
 ((3929, 6376), 0.6015625),
 ((3929, 6548), 0.6015625),
 ((3929, 6606), 0.6015625),
 ((3929, 6680), 0.6015625),
 ((3929, 6747), 0.6015625),
 ((3929, 6814), 0.6015625),
 ((3929, 6924), 0.6015625),
 ((3929, 7193), 0.6015625),
 ((3929, 7306), 0.6015625),
 ((3929, 7371), 0.6015625),
 ((3929, 7537), 0.6015625),
 ((3929, 7611), 0.6015625),
 ((3929, 7791), 0.6015625),
 ((3929, 7824), 0.6015625),
 ((3929, 7966), 0.6015625),
 ((3929, 8023), 0.6015625),
 ((3929, 8075), 0.6015625),
 ((3929, 8123), 0.6015625),
 ((3929, 8210), 0.6015625),
 ((3929, 8285), 0.6015625),
 ((3929, 8402), 0.6015625),
 ((3929, 8564), 0.6015625),
 ((3929, 8648), 0.6015625),
 ((3929, 8994), 0.6015625),
 ((4008, 4936), 0.6015625),
 ((4008, 5040), 0.6015625),
 ((4008, 5099), 0.6015625),
 ((4008, 5168), 0.6015625),
 ((4008, 5242), 0.6015625),
 ((4008, 5303), 0.6015625),
 ((4008, 5404), 0.6015625),
 ((4008, 5465), 0.6015625),
 ((4008, 5542), 0.6015625),
 ((4008, 5626), 0.6015625),
 ((4008, 5696), 0.6015625),
 ((4008, 5794), 0.6015625),
 ((4008, 5852), 0.6015625),
 ((4008, 5932), 0.6015625),
 ((4008, 6000), 0.6015625),
 ((4008, 6067), 0.6015625),
 ((4008, 6171), 0.6015625),
 ((4008, 6233), 0.6015625),
 ((4008, 6303), 0.6015625),
 ((4008, 6376), 0.6015625),
 ((4008, 6548), 0.6015625),
 ((4008, 6606), 0.6015625),
 ((4008, 6680), 0.6015625),
 ((4008, 6747), 0.6015625),
 ((4008, 6814), 0.6015625),
 ((4008, 6924), 0.6015625),
 ((4008, 7193), 0.6015625),
 ((4008, 7306), 0.6015625),
 ((4008, 7371), 0.6015625),
 ((4008, 7537), 0.6015625),
 ((4008, 7611), 0.6015625),
 ((4008, 7791), 0.6015625),
 ((4008, 7824), 0.6015625),
 ((4008, 7966), 0.6015625),
 ((4008, 8023), 0.6015625),
 ((4008, 8075), 0.6015625),
 ((4008, 8123), 0.6015625),
 ((4008, 8210), 0.6015625),
 ((4008, 8285), 0.6015625),
 ((4008, 8402), 0.6015625),
 ((4008, 8564), 0.6015625),
 ((4008, 8648), 0.6015625),
 ((4008, 8994), 0.6015625),
 ((4078, 4936), 0.6015625),
 ((4078, 5040), 0.6015625),
 ((4078, 5099), 0.6015625),
 ((4078, 5168), 0.6015625),
 ((4078, 5242), 0.6015625),
 ((4078, 5303), 0.6015625),
 ((4078, 5404), 0.6015625),
 ((4078, 5465), 0.6015625),
 ((4078, 5542), 0.6015625),
 ((4078, 5626), 0.6015625),
 ((4078, 5696), 0.6015625),
 ((4078, 5794), 0.6015625),
 ((4078, 5852), 0.6015625),
 ((4078, 5932), 0.6015625),
 ((4078, 6000), 0.6015625),
 ((4078, 6067), 0.6015625),
 ((4078, 6171), 0.6015625),
 ((4078, 6233), 0.6015625),
 ((4078, 6303), 0.6015625),
 ((4078, 6376), 0.6015625),
 ((4078, 6548), 0.6015625),
 ((4078, 6606), 0.6015625),
 ((4078, 6680), 0.6015625),
 ((4078, 6747), 0.6015625),
 ((4078, 6814), 0.6015625),
 ((4078, 6924), 0.6015625),
 ((4078, 7193), 0.6015625),
 ((4078, 7306), 0.6015625),
 ((4078, 7371), 0.6015625),
 ((4078, 7537), 0.6015625),
 ((4078, 7611), 0.6015625),
 ((4078, 7791), 0.6015625),
 ((4078, 7824), 0.6015625),
 ((4078, 7966), 0.6015625),
 ((4078, 8023), 0.6015625),
 ((4078, 8075), 0.6015625),
 ((4078, 8123), 0.6015625),
 ((4078, 8210), 0.6015625),
 ((4078, 8285), 0.6015625),
 ((4078, 8402), 0.6015625),
 ((4078, 8564), 0.6015625),
 ((4078, 8648), 0.6015625),
 ((4078, 8994), 0.6015625),
 ((4152, 4936), 0.6015625),
 ((4152, 5040), 0.6015625),
 ((4152, 5099), 0.6015625),
 ((4152, 5168), 0.6015625),
 ((4152, 5242), 0.6015625),
 ((4152, 5303), 0.6015625),
 ((4152, 5404), 0.6015625),
 ((4152, 5465), 0.6015625),
 ((4152, 5542), 0.6015625),
 ((4152, 5626), 0.6015625),
 ((4152, 5696), 0.6015625),
 ((4152, 5794), 0.6015625),
 ((4152, 5852), 0.6015625),
 ((4152, 5932), 0.6015625),
 ((4152, 6000), 0.6015625),
 ((4152, 6067), 0.6015625),
 ((4152, 6171), 0.6015625),
 ((4152, 6233), 0.6015625),
 ((4152, 6303), 0.6015625),
 ((4152, 6376), 0.6015625),
 ((4152, 6548), 0.6015625),
 ((4152, 6606), 0.6015625),
 ((4152, 6680), 0.6015625),
 ((4152, 6747), 0.6015625),
 ((4152, 6814), 0.6015625),
 ((4152, 6924), 0.6015625),
 ((4152, 7193), 0.6015625),
 ((4152, 7306), 0.6015625),
 ((4152, 7371), 0.6015625),
 ((4152, 7537), 0.6015625),
 ((4152, 7611), 0.6015625),
 ((4152, 7791), 0.6015625),
 ((4152, 7824), 0.6015625),
 ((4152, 7966), 0.6015625),
 ((4152, 8023), 0.6015625),
 ((4152, 8075), 0.6015625),
 ((4152, 8123), 0.6015625),
 ((4152, 8210), 0.6015625),
 ((4152, 8285), 0.6015625),
 ((4152, 8402), 0.6015625),
 ((4152, 8564), 0.6015625),
 ((4152, 8648), 0.6015625),
 ((4152, 8994), 0.6015625),
 ((4260, 4936), 0.6015625),
 ((4260, 5040), 0.6015625),
 ((4260, 5099), 0.6015625),
 ((4260, 5168), 0.6015625),
 ((4260, 5242), 0.6015625),
 ((4260, 5303), 0.6015625),
 ((4260, 5404), 0.6015625),
 ((4260, 5465), 0.6015625),
 ((4260, 5542), 0.6015625),
 ((4260, 5626), 0.6015625),
 ((4260, 5696), 0.6015625),
 ((4260, 5794), 0.6015625),
 ((4260, 5852), 0.6015625),
 ((4260, 5932), 0.6015625),
 ((4260, 6000), 0.6015625),
 ((4260, 6067), 0.6015625),
 ((4260, 6171), 0.6015625),
 ((4260, 6233), 0.6015625),
 ((4260, 6303), 0.6015625),
 ((4260, 6376), 0.6015625),
 ((4260, 6548), 0.6015625),
 ((4260, 6606), 0.6015625),
 ((4260, 6680), 0.6015625),
 ((4260, 6747), 0.6015625),
 ((4260, 6814), 0.6015625),
 ((4260, 6924), 0.6015625),
 ((4260, 7193), 0.6015625),
 ((4260, 7306), 0.6015625),
 ((4260, 7371), 0.6015625),
 ((4260, 7537), 0.6015625),
 ((4260, 7611), 0.6015625),
 ((4260, 7791), 0.6015625),
 ((4260, 7824), 0.6015625),
 ((4260, 7966), 0.6015625),
 ((4260, 8023), 0.6015625),
 ((4260, 8075), 0.6015625),
 ((4260, 8123), 0.6015625),
 ((4260, 8210), 0.6015625),
 ((4260, 8285), 0.6015625),
 ((4260, 8402), 0.6015625),
 ((4260, 8564), 0.6015625),
 ((4260, 8648), 0.6015625),
 ((4260, 8994), 0.6015625),
 ((4331, 4936), 0.6015625),
 ((4331, 5040), 0.6015625),
 ((4331, 5099), 0.6015625),
 ((4331, 5168), 0.6015625),
 ((4331, 5242), 0.6015625),
 ((4331, 5303), 0.6015625),
 ((4331, 5404), 0.6015625),
 ((4331, 5465), 0.6015625),
 ((4331, 5542), 0.6015625),
 ((4331, 5626), 0.6015625),
 ((4331, 5696), 0.6015625),
 ((4331, 5794), 0.6015625),

In [110]:
lsh = MinHashLSH(threshold=0.3)

for i in range(len(minhashs_list)):
    lsh.insert(i, minhashs_list[i])

In [111]:
lsh.query(minhashs_list[10])

[2952, 10]

In [112]:
def lsh_sim_total(minhash_list):
    similar_pairs = []

    for doc_id, minhash in minhash_list.items():
        candidates = lsh.query(minhash)
        
        for candidate_id in candidates:
            if candidate_id != doc_id:
                pair = tuple(sorted([doc_id, candidate_id]))
                similar_pairs.append(pair)

    similar_pairs = set(similar_pairs)
    return similar_pairs

In [113]:
lsh_total = lsh_sim_total(minhashs_list)

In [114]:
lsh_total

{(5383, 5931),
 (11833, 12110),
 (7561, 8525),
 (3660, 16187),
 (190, 3656),
 (12307, 15184),
 (7386, 11153),
 (1257, 14414),
 (4249, 13549),
 (4013, 14770),
 (9858, 12504),
 (2301, 10663),
 (7282, 12493),
 (11944, 13097),
 (6824, 15587),
 (3896, 5325),
 (625, 10939),
 (766, 12110),
 (2865, 7029),
 (816, 1085),
 (9616, 16354),
 (6115, 12646),
 (86, 5935),
 (1521, 5038),
 (9864, 16456),
 (5268, 9741),
 (7782, 8874),
 (1636, 5550),
 (10992, 15816),
 (2804, 4309),
 (4761, 16326),
 (2509, 14749),
 (5037, 13780),
 (5307, 7225),
 (9546, 14080),
 (9195, 13099),
 (196, 3070),
 (1429, 12804),
 (7946, 14351),
 (4474, 11573),
 (6747, 7611),
 (10776, 15410),
 (3042, 9735),
 (4630, 12086),
 (7162, 15932),
 (8339, 16497),
 (4483, 16762),
 (2246, 16217),
 (3430, 11537),
 (5479, 10311),
 (12645, 16468),
 (5193, 7473),
 (8904, 16683),
 (6029, 7745),
 (10597, 14132),
 (4630, 9053),
 (2109, 8749),
 (6474, 16497),
 (5939, 12955),
 (11009, 16520),
 (3444, 4238),
 (6114, 9546),
 (8712, 13480),
 (1444, 16468),
 (8662, 11673),
 (13639, 14293),
 (11344, 12080),
 (15392, 16711),
 (4967, 15239),
 (10084, 13732),
 (4136, 12867),
 (3773, 12815),
 (858, 13338),
 (898, 3877),
 (10335, 11099),
 (1875, 6074),
 (1777, 2533),
 (13034, 15647),
 (1319, 1655),
 (13108, 15596),
 (1133, 2431),
 (6680, 6924),
 (7394, 12683),
 (5577, 7062),
 (11098, 16750),
 (11368, 14359),
 (143, 12080),
 (6576, 8264),
 (6910, 7386),
 (11383, 12947),
 (11703, 16335),
 (7871, 9050),
 (8642, 8927),
 (7654, 15239),
 (6983, 14280),
 (3623, 4361),
 (9925, 13860),
 (12767, 16434),
 (3868, 16435),
 (7677, 15600),
 (659, 5931),
 (8584, 12140),
 (6538, 8911),
 (7013, 9958),
 (9864, 10174),
 (8874, 15851),
 (3460, 6060),
 (4511, 10650),
 (10385, 11566),
 (3423, 15038),
 (5245, 14587),
 (4053, 6574),
 (13674, 16357),
 (6587, 15219),
 (13290, 15428),
 (4968, 7139),
 (2874, 2930),
 (8503, 14403),
 (2323, 3581),
 (7797, 13423),
 (4325, 10645),
 (9511, 15913),
 (34, 6818),
 (920, 13061),
 (10717, 10992),
 (4584, 16009),
 (5286, 16281),
 (9414, 15980),
 (13149, 15196),
 (9515, 9616),
 (1683, 4160),
 (2459, 3627),
 (4181, 10142),
 (5853, 13130),
 (8148, 8927),
 (6350, 13936),
 (9306, 13414),
 (2909, 6307),
 (4533, 8315),
 (8179, 12212),
 (9862, 11417),
 (6308, 16154),
 (7181, 7448),
 (8533, 15184),
 (6050, 11200),
 (8712, 12675),
 (1934, 10572),
 (12715, 15089),
 (7944, 8373),
 (254, 15802),
 (3503, 4013),
 (812, 5772),
 (910, 2143),
 (1555, 5291),
 (9688, 10483),
 (4868, 13674),
 (6262, 6360),
 (7438, 11396),
 (6074, 6309),
 (7330, 7921),
 (1082, 9016),
 (6989, 7628),
 (1932, 9186),
 (9960, 12110),
 (5402, 15301),
 (7255, 14163),
 (7033, 11118),
 (13487, 14787),
 (3332, 5070),
 (4677, 14079),
 (4820, 13633),
 (8691, 16120),
 (5885, 7541),
 (9735, 15375),
 (9186, 16099),
 (7827, 12110),
 (6820, 13454),
 (1225, 11953),
 (3396, 16574),
 (516, 7292),
 (5015, 6904),
 (8969, 9456),
 (9713, 12583),
 (8722, 12208),
 (4243, 11528),
 (3381, 14007),
 (124, 4967),
 (6209, 16683),
 (13936, 14771),
 (1512, 5752),
 (6429, 16457),
 (1080, 3843),
 (12702, 15392),
 (5873, 6376),
 (8772, 15708),
 (1454, 16327),
 (6607, 10313),
 (5315, 7546),
 (90, 660),
 (143, 6148),
 (2701, 11215),
 (7295, 12407),
 (79, 4443),
 (1199, 4474),
 (2145, 11522),
 (8375, 9067),
 (906, 2909),
 (6587, 14764),
 (718, 3612),
 (2712, 14787),
 (5323, 6751),
 (9632, 13533),
 (14651, 15655),
 (1638, 13411),
 (6419, 11955),
 (5512, 12971),
 (1792, 13097),
 (5923, 12505),
 (5063, 5231),
 (6350, 7654),
 (6217, 10508),
 (8916, 16746),
 (11795, 14314),
 (7089, 10437),
 (7335, 13876),
 (7691, 12757),
 (8591, 14734),
 (9341, 9570),
 (12398, 15516),
 (7827, 7922),
 (10442, 13523),
 (6784, 7357),
 (10832, 11234),
 (7857, 15678),
 (6171, 6376),
 (3736, 8290),
 (4670, 16267),
 (7356, 11720),
 (9894, 10685),
 (11664, 14770),
 (7753, 10602),
 (8885, 16120),
 (10776, 16028),
 (12084, 15356),
 (6213, 7541),
 (1465, 12298),
 (70, 8652),
 (3926, 5943),
 (6522, 9050),
 (8251, 12572),
 (35, 16013),
 (924, 15357),
 (9594, 12086),
 (11251, 13288),
 (13699, 16497),
 (3522, 8711),
 (8073, 8513),
 (14587, 15239),
 (9643, 15920),
 (10572, 16383),
 (1851, 2161),
 (268, 908),
 (10687, 12923),
 (142, 4741),
 (1561, 13699),
 (7905, 8148),
 (9515, 14422),
 (3567, 13557),
 (5931, 15375),
 (3102, 11508),
 (4150, 9219),
 (5963, 14132),
 (6443, 8353),
 (8024, 13697),
 (901, 1760),
 (8361, 8364),
 (9032, 16705),
 (682, 898),
 (5224, 8316),
 (6607, 10447),
 (8505, 11526),
 (2701, 11349),
 (10992, 15629),
 (66, 12451),
 (6234, 15534),
 (12590, 16224),
 (8565, 14960),
 (6681, 14533),
 (7371, 8564),
 (7796, 13466),
 (2089, 5308),
 (2381, 13064),
 (5428, 14912),
 (9141, 9643),
 (5839, 13692),
 (2281, 3034),
 (350, 13149),
 (3118, 12576),
 (1919, 5836),
 (13446, 16559),
 (673, 7386),
 (10163, 16686),
 (5530, 7460),
 (7343, 11619),
 (3871, 4677),
 (2223, 7001),
 (8021, 10551),
 (5412, 15318),
 (5094, 10313),
 (7255, 13492),
 (8874, 10992),
 (9781, 14140),
 (4875, 15113),
 (6661, 8589),
 (1919, 9219),
 (6437, 9827),
 (2049, 14927),
 (740, 5575),
 (5550, 16191),
 (12789, 13027),
 (11613, 15316),
 (3327, 7438),
 (3332, 7782),
 (4118, 8691),
 (6587, 16187),
 (8703, 13739),
 (1413, 8300),
 (3333, 4220),
 (673, 5292),
 (5932, 8564),
 (2088, 6934),
 (2781, 4646),
 (2168, 16497),
 (6203, 9781),
 (5845, 10073),
 (7287, 10155),
 (1497, 3460),
 (2180, 2736),
 (12754, 16574),
 (8210, 8329),
 (669, 4769),
 (3449, 8717),
 (5063, 10037),
 (5546, 16607),
 (8476, 15618),
 (11970, 13703),
 (1511, 15409),
 (412, 3423),
 (13601, 15692),
 (5836, 9206),
 (6751, 16187),
 (6400, 11234),
 (8833, 12657),
 (10758, 16091),
 (2902, 7043),
 (1193, 13787),
 (6511, 14256),
 (9250, 15197),
 (1561, 5323),
 (124, 5585),
 (3192, 6058),
 (2887, 11838),
 (143, 3383),
 (3436, 4698),
 (4487, 12506),
 (3327, 12110),
 (6397, 8492),
 (8513, 10208),
 (13580, 15754),
 (4669, 7824),
 (6090, 11193),
 (1384, 11288),
 (10551, 15239),
 (2411, 8876),
 (1308, 8260),
 (2428, 8291),
 (2113, 9219),
 (2701, 11833),
 (4689, 5258),
 (2572, 9733),
 (11349, 15219),
 (12250, 13634),
 (5278, 14698),
 (3740, 8492),
 (4263, 10519),
 (9442, 9890),
 (1388, 3301),
 (6272, 9894),
 (5403, 7230),
 (7369, 16357),
 (4537, 12219),
 (4642, 8071),
 (8179, 8992),
 (9753, 15609),
 (9185, 16091),
 (9918, 10758),
 (4942, 7020),
 (766, 10313),
 (809, 11703),
 (4150, 10992),
 (5530, 7944),
 (3928, 5695),
 (13167, 15184),
 (2732, 6608),
 (3642, 5863),
 (6114, 12876),
 (2652, 11540),
 (2636, 16699),
 (3871, 6100),
 (5851, 13405),
 (3327, 7922),
 (1085, 7033),
 (5297, 7369),
 (8642, 8874),
 (14755, 16222),
 (3447, 5772),
 (6198, 12954),
 (740, 13414),
 (979, 11710),
 (6012, 9566),
 (573, 14994),
 (9129, 9901),
 (10151, 13561),
 (175, 14167),
 (1051, 5170),
 (1488, 5171),
 (1777, 2830),
 (3222, 6593),
 (3155, 5371),
 (10479, 14558),
 (682, 4549),
 (5081, 9407),
 (1543, 14677),
 (2701, 8584),
 (757, 1690),
 (2286, 12506),
 (9175, 15911),
 (12876, 13291),
 (11150, 16456),
 (2036, 12331),
 (6303, 8402),
 (7213, 15039),
 (1468, 12813),
 (10239, 16010),
 (12947, 15386),
 (1051, 15908),
 (34, 6176),
 (4332, 12702),
 (3864, 10382),
 (8148, 8874),
 (9815, 15682),
 (4677, 16120),
 (14770, 16099),
 (1473, 16540),
 (4266, 7918),
 (6203, 14587),
 (1860, 14734),
 (11707, 12028),
 (2896, 7712),
 (4630, 5162),
 (2381, 7266),
 (1388, 9262),
 (8833, 14080),
 (3332, 10494),
 (1085, 9261),
 (3349, 9909),
 (1990, 5166),
 (3671, 9960),
 (4118, 15375),
 (16007, 16126),
 (35, 12443),
 (1766, 6212),
 (1444, 6161),
 (12935, 14221),
 (7961, 11118),
 (9399, 16154),
 (3437, 15391),
 (8991, 14639),
 (4967, 8904),
 (12876, 14580),
 (10281, 15081),
 (7361, 15260),
 (4875, 9315),
 (9701, 10076),
 (1595, 15375),
 (3562, 5479),
 (12314, 12598),
 (7266, 9546),
 (6203, 14140),
 (2603, 4053),
 (2489, 13373),
 (10717, 13167),
 (13325, 13625),
 (15410, 16028),
 (498, 14015),
 (956, 1095),
 (4013, 11013),
 (5037, 15500),
 (484, 7701),
 (5045, 15361),
 (5496, 11096),
 (5610, 12918),
 (6100, 7827),
 (7058, 12226),
 (1473, 8969),
 (11375, 12524),
 (3885, 9515),
 (9539, 15408),
 (3384, 11973),
 (2782, 3237),
 (13277, 16028),
 (11196, 13552),
 (2113, 10992),
 (15779, 16275),
 (6988, 15055),
 (605, 3682),
 (14068, 15776),
 (15687, 16686),
 (219, 12506),
 (971, 8169),
 (9116, 12432),
 (5659, 10686),
 (234, 5432),
 (382, 5330),
 (9960, 10313),
 (7905, 9250),
 (1568, 13528),
 (4008, 5542),
 (4238, 14864),
 (7690, 9850),
 (575, 9108),
 (809, 7060),
 (9250, 9399),
 (124, 6203),
 (1123, 14575),
 (1562, 8795),
 (4408, 6415),
 (757, 2174),
 (5889, 16251),
 (8380, 13680),
 (2926, 9186),
 (14080, 15197),
 (94, 5802),
 (10508, 14467),
 (15069, 15711),
 (3866, 13945),
 (3478, 15526),
 (3967, 12307),
 (1801, 5778),
 (5496, 16707),
 (14285, 14848),
 (8354, 13398),
 (7449, 11077),
 (2301, 6101),
 (8992, 15375),
 (14140, 16187),
 (7292, 13345),
 (1095, 2354),
 (3787, 10619),
 (2223, 13580),
 (3450, 5372),
 (7438, 8444),
 (1815, 4895),
 (13210, 13247),
 (1932, 6234),
 (87, 11397),
 (3666, 3684),
 (5051, 7396),
 (906, 5084),
 (3027, 14314),
 (2776, 4115),
 (1561, 7230),
 (2387, 2842),
 (7922, 8264),
 (9632, 15708),
 (2168, 3478),
 (6920, 8454),
 (513, 659),
 (8183, 14455),
 (10101, 14466),
 (11796, 11988),
 (3840, 8186),
 (1555, 6661),
 (3332, 11917),
 (2432, 14104),
 (3205, 3474),
 (3671, 4967),
 (3910, 7427),
 (3046, 15495),
 (8487, 10894),
 (10599, 11710),
 (10470, 13020),
 (8589, 12110),
 (4630, 13940),
 (695, 9186),
 (1851, 8874),
 (4201, 11548),
 (928, 14083),
 (503, 12399),
 (1143, 11793),
 (2652, 13097),
 (3013, 16486),
 (2646, 14972),
 (6576, 12212),
 (5542, 7791),
 (1805, 5496),
 (7950, 13291),
 (9960, 10447),
 (473, 1610),
 (4559, 12195),
 (5889, 9030),
 (13277, 14068),
 (14555, 14685),
 (11659, 15258),
 (2342, 15500),
 (3161, 16357),
 (3542, 4183),
 (6100, 9250),
 (3388, 16548),
 (4183, 12847),
 (1791, 15397),
 (6747, 7371),
 (7827, 10447),
 (9000, 11802),
 (13561, 16456),
 (9986, 12799),
 (1555, 7950),
 (7950, 14230),
 (7654, 16154),
 (6393, 7782),
 (1782, 4731),
 (2652, 13447),
 (5104, 15112),
 (7969, 8056),
 (9006, 10304),
 (1561, 3042),
 (1177, 2113),
 (3885, 7905),
 (4587, 8177),
 (1311, 2113),
 (2808, 2848),
 (3769, 14146),
 (9827, 15371),
 (11164, 13185),
 (5245, 6642),
 (966, 2832),
 (603, 2780),
 (4477, 11200),
 (1177, 5496),
 (12789, 16357),
 (1311, 5496),
 (2768, 15500),
 (3310, 4183),
 (7272, 13204),
 (13411, 15357),
 (2198, 8931),
 (4756, 11554),
 (10862, 13759),
 (15184, 16707),
 (1162, 1431),
 (5836, 14630),
 (10239, 14534),
 (11099, 15392),
 (1163, 4285),
 (5550, 7628),
 (9096, 10355),
 (10216, 14550),
 (6642, 16191),
 (10789, 11968),
 (10992, 14771),
 (2833, 8166),
 (6544, 9240),
 (5585, 14230),
 (497, 16475),
 (998, 11573),
 (1731, 11158),
 (4021, 13027),
 (1404, 10763),
 (5542, 6986),
 (6442, 15379),
 (10509, 13082),
 (13073, 13268),
 (3444, 11703),
 (3838, 6904),
 (2322, 10845),
 (3864, 5873),
 (722, 3761),
 (4514, 16343),
 (5727, 10149),
 (1990, 3690),
 (13347, 14002),
 (8763, 13528),
 (2682, 14763),
 (1555, 13561),
 (7782, 8179),
 (681, 6389),
 (7071, 16489),
 (5472, 12259),
 (8927, 9206),
 (1177, 14140),
 (4914, 7767),
 (4630, 8008),
 (11087, 15166),
 (3967, 14080),
 (1085, 14551),
 (3043, 15681),
 (7274, 12095),
 (4084, 8249),
 (5015, 5375),
 (13477, 15953),
 (1078, 6964),
 (4820, 15487),
 (8813, 13241),
 (10208, 15197),
 (12873, 16189),
 (7338, 14739),
 (4284, 4338),
 (10383, 15952),
 (285, 8459),
 (3740, 5406),
 (5070, 9219),
 (6307, 10027),
 (4975, 9359),
 (5496, 6587),
 (8383, 14596),
 (7369, 13271),
 (1051, 13627),
 (9186, 12476),
 (3045, 14414),
 (2532, 10631),
 (12735, 13222),
 (11917, 15219),
 (1511, 8135),
 (4761, 5616),
 (812, 12298),
 (10452, 11743),
 (2637, 15528),
 (5793, 7712),
 (9306, 14463),
 (7448, 8841),
 (3000, 13890),
 (1548, 2540),
 (4338, 14558),
 (8916, 15217),
 (6715, 15083),
 (1669, 6442),
 (2025, 5323),
 (48, 1699),
 (3332, 11596),
 (5546, 16099),
 (6474, 7292),
 (5099, 8994),
 (6603, 7702),
 (8008, 16762),
 (742, 13407),
 (6848, 15612),
 (3997, 11986),
 (11411, 15239),
 (3593, 8927),
 (2853, 9117),
 (3871, 12813),
 (12555, 15856),
 (8719, 15053),
 (6424, 12840),
 (12212, 16456),
 (3671, 5585),
 (4331, 8075),
 (4159, 4585),
 (14587, 16154),
 (4150, 13167),
 (382, 11559),
 (4656, 5391),
 (4150, 6751),
 (5294, 13784),
 (6682, 10597),
 (6393, 10494),
 (479, 14875),
 (3640, 7403),
 (13660, 16703),
 (6138, 9221),
 (1895, 7320),
 (5453, 9118),
 (10274, 13699),
 (7641, 13154),
 (5351, 11285),
 (9594, 13940),
 (9616, 13699),
 (1805, 6114),
 (2233, 7315),
 (34, 7062),
 (9351, 11738),
 (11066, 15362),
 (3623, 8927),
 (6522, 7871),
 (8712, 15952),
 (2334, 4923),
 (30, 8074),
 (3877, 9975),
 (3973, 16099),
 (3326, 16288),
 (6700, 12307),
 (7230, 12307),
 (673, 3979),
 (3742, 12002),
 (13890, 14132),
 (6741, 9864),
 (5297, 15371),
 (4337, 4483),
 (2420, 8080),
 (2168, 15184),
 (2053, 12982),
 (1561, 3660),
 (3868, 9108),
 (2293, 14132),
 (8073, 10717),
 (5700, 14071),
 (4002, 9862),
 (12071, 12787),
 (3327, 10447),
 (154, 12432),
 (1770, 3245),
 (5235, 15432),
 (5245, 16120),
 (12368, 15225),
 (452, 3229),
 (734, 2161),
 (1919, 13167),
 (124, 13721),
 (1919, 6751),
 (7230, 12657),
 (6688, 11142),
 (9016, 13303),
 (1177, 6114),
 (7266, 12876),
 (9909, 16553),
 (1311, 6114),
 (10174, 13064),
 (1646, 11288),
 (11340, 15722),
 (10717, 16497),
 (1555, 6474),
 (1436, 5062),
 (7408, 11239),
 (10159, 11251),
 (4163, 5242),
 (1031, 7228),
 (12008, 13377),
 (11318, 12176),
 (6576, 8642),
 (2455, 7670),
 (2930, 8717),
 (2109, 7033),
 (734, 8927),
 (5471, 7953),
 (6114, 10274),
 (12876, 15816),
 (6625, 10978),
 (501, 13829),
 (7282, 9033),
 (6071, 7194),
 (5162, 9827),
 (5250, 10428),
 (7438, 9546),
 (682, 1597),
 (9241, 13771),
 (5836, 16187),
 (7178, 15099),
 (4585, 9257),
 (5070, 10992),
 (8525, 11349),
 (882, 12208),
 (3332, 16052),
 (3717, 15863),
 (2353, 10776),
 (8833, 9250),
 (8955, 10933),
 (15113, 15580),
 (3509, 4048),
 (6576, 8992),
 (11108, 15722),
 (4776, 13174),
 (2902, 13435),
 (320, 1366),
 (7164, 13888),
 (7193, 8402),
 (2334, 7501),
 (3332, 6603),
 (13880, 16022),
 (10993, 16149),
 (12206, 12207),
 (1717, 12228),
 (11187, 12982),
 (6139, 9930),
 (5327, 7800),
 (7268, 9515),
 (7921, 12524),
 (8561, 8720),
 (14025, 15622),
 (12817, 13492),
 (2867, 8903),
 (4689, 9206),
 (3376, 15196),
 (11791, 13096),
 (2113, 6751),
 (3866, 4443),
 (6393, 11917),
 (1553, 12012),
 (4051, 9858),
 (1773, 14230),
 (9206, 13561),
 (10551, 16154),
 (1869, 7522),
 (6182, 15080),
 (1468, 11150),
 (575, 3928),
 (3329, 14037),
 (6338, 15593),
 (6555, 14130),
 (3100, 14739),
 (4072, 7702),
 (6238, 11979),
 (7238, 15126),
 (7666, 9911),
 (2246, 10663),
 (4223, 12035),
 (10597, 14994),
 (4360, 5890),
 (3759, 12840),
 (3694, 6029),
 (10208, 13721),
 (3759, 6424),
 (6567, 14140),
 (8922, 14152),
 (176, 16647),
 (14543, 14622),
 (1661, 15113),
 (3555, 14730),
 (6836, 13776),
 (4749, 14710),
 (9293, 9369),
 (8073, 12140),
 (8708, 11190),
 (5886, 7740),
 (6025, 8838),
 (6818, 14890),
 (252, 14390),
 (3740, 11285),
 (5496, 14910),
 (13994, 14565),
 (2074, 12249),
 (5546, 7857),
 (9484, 16292),
 (9539, 16191),
 (7230, 14080),
 (11096, 12813),
 (11996, 14790),
 (2161, 10151),
 (5588, 9022),
 (2646, 3026),
 (6114, 10758),
 (4338, 15526),
 (3327, 6393),
 (3671, 6203),
 (4605, 13426),
 (6613, 9947),
 (8844, 14619),
 (3161, 13271),
 (5169, 9038),
 (10066, 16647),
 (11582, 12706),
 (8691, 8927),
 (516, 15375),
 (1989, 14770),
 (1805, 5793),
 (4666, 14833),
 (8186, 16339),
 (10650, 12911),
 (1897, 15181),
 (6618, 13674),
 (2719, 15555),
 (7712, 16456),
 (8589, 10313),
 (2025, 7230),
 (5497, 11728),
 (4335, 16167),
 (3967, 5383),
 (7905, 13064),
 (4868, 16630),
 (2432, 13246),
 (4875, 15357),
 (6661, 8833),
 (8533, 8691),
 (8712, 10154),
 (6877, 16005),
 (9228, 13454),
 (1965, 14534),
 (5905, 12462),
 (8264, 13936),
 (107, 1742),
 (12789, 13271),
 ...}