In [9]:
import os
os.environ['KAGGLE_USERNAME'] = "anastasiakhromova"
os.environ['KAGGLE_KEY'] = "KGAT_a4177bc6807822bc6d28ff5e23b1caff"
#!kaggle datasets download benjaminawd/new-york-times-articles-comments-2020

In [10]:
import pandas as pd 
import numpy as np

# EDA

In [11]:
data_path = "D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020"

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\2168738046.py:1: SyntaxWarning: invalid escape sequence '\P'
  data_path = "D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020"

In [12]:
test = pd.read_csv(data_path+'\\test.csv')
test

,newsdesk,section,subsection,material,headline,abstract,keywords,word_count,pub_date,is_popular,uniqueID
0,OpEd,Opinion,NaN,Op-Ed,Anyone Else Want to See Trump ‘Shut Up’?,Our president as a terrible toddler.,"['Presidential Election of 2020', 'Biden, Jose...",925,2020-10-01 00:05:51+00:00,1,nyt://article/e467c2ae-2df3-5836-a6ca-b23d0d33...
1,OpEd,Opinion,NaN,Op-Ed,Trump Calls on Extremists to ‘Stand By’,"Instead of condemning violent groups, the pres...","['Presidential Election of 2020', 'United Stat...",902,2020-10-01 00:43:28+00:00,1,nyt://article/9a7ef9e0-1334-56b2-a7f1-288c4887...
2,OpEd,Opinion,NaN,Op-Ed,"Can Mike Espy Make History, Again?",If the Democratic Party claims to value Black ...,"['Black People', 'Blacks', 'Presidential Elect...",1412,2020-10-01 00:45:17+00:00,1,nyt://article/4bb2b763-0088-5e10-b204-19e404f7...
3,Games,Crosswords & Games,NaN,News,In Which Rikishi Wear Mawashi,Adam Fromm is on the line.,['Crossword Puzzles'],849,2020-10-01 02:00:05+00:00,1,nyt://article/0d96205f-edb8-5f1f-8c44-1ddf6ed5...
4,Sports,Sports,Pro Football,News,N.F.L. Week 4 Predictions: Our Picks Against t...,Tom Brady and the Buccaneers are building mome...,"['Football', 'New England Patriots', 'Kansas C...",2690,2020-10-01 04:01:16+00:00,0,nyt://article/afc8295b-3c22-5a5f-9539-3f77b7b8...
...,...,...,...,...,...,...,...,...,...,...,...
3990,Editorial,Opinion,NaN,Op-Ed,What It Takes to Heal From Covid-19,"Survivors can get better, but they need help.","['Chronic Condition (Health)', 'Coronavirus (2...",1002,2020-12-31 15:27:47+00:00,1,nyt://article/e8adbb75-a8b3-5a8c-886b-b9c1195f...
3991,Sports,Sports,Baseball,News,Padres Jolt M.L.B. With Bold Moves to Set Up W...,While many teams continued to assess the finan...,"['San Diego Padres', 'Major League Baseball', ...",1100,2020-12-31 15:47:44+00:00,0,nyt://article/1f11417d-2c57-51b9-b75d-8f67f0a9...
3992,Business,Business Day,NaN,News,"Their Finances Ravaged, Customers Fear Banks W...",Banks have the power to decide whether to let ...,"['Banking and Financial Institutions', 'Corona...",1429,2020-12-31 16:21:40+00:00,1,nyt://article/c4b9edab-bdde-5d81-b496-06fedb52...
3993,Dining,Food,"Wine, Beer & Cocktails",News,Should Wine Be Among Your Health Resolutions?,The new category of ‘clean wines’ is an effort...,"['Wines', 'Grapes', 'Diet and Nutrition', 'Dia...",1307,2020-12-31 17:28:11+00:00,1,nyt://article/efcaf652-ffad-5b4e-9f17-4fd9aff5...
3994,Business,Technology,NaN,News,Microsoft Says Russian Hackers Viewed Some of ...,The hackers gained more access than the compan...,"['Microsoft Corp', 'US Federal Government Data...",340,2020-12-31 18:02:02+00:00,1,nyt://article/12048b2b-62e3-5bed-8c77-483a4299...

In [13]:
df_main = pd.read_csv('D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020\\nyt-articles-2020.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\3702147964.py:1: SyntaxWarning: invalid escape sequence '\P'
  df_main = pd.read_csv('D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020\\nyt-articles-2020.csv')

In [14]:
abstract = df_main[['abstract']]

In [15]:
for a in abstract.abstract[:5]:
    print(a)

Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.
Christina Iverson and Jeff Chen ring in the New Year.
All year long, Earth passes through streams of cosmic debris. Here’s a list of major meteor showers and how to spot one.
Never miss an eclipse, a meteor shower, a rocket launch or any other astronomical and space event that's out of this world.
A year full of highs and lows in space just ended, and the 12 months to come  will be full of new highlights in orbit and beyond.

## Tokenization

In [16]:
#!pip install spacy 
import spacy

In [17]:
#!pip install nltk

In [18]:
#import sys
#!{sys.executable} -m pip install spacy
#!{sys.executable} -m spacy download en_core_web_sm

In [19]:
nlp = spacy.load("en_core_web_sm")

In [20]:
abstract1 = abstract.abstract.iloc[0]
abstract1

'Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.'

In [21]:
with open("data\stopwords.txt", "r", encoding="utf-8") as f:
    stopwords = set(line.strip() for line in f)

print(stopwords)

{'such', 'not', 'me', 'has', 'then', 'herself', 'off', 'him', 'these', 'yourself', 'as', 'being', 'after', 'above', 'down', 'of', 't', 'very', 'more', 'at', 'other', 'they', 'through', 'have', 'does', 'hers', 'the', 's', 'whom', 'ourselves', 'all', 'did', 'once', 'because', 'to', 'your', 'only', 'if', 'which', 'each', 'and', 'it', 'their', 'our', 'been', 'can', 'we', 'myself', 'her', 'you', 'its', 'just', 'when', 'about', 'his', 'for', 'before', 'up', 'both', 'over', 'during', 'how', 'was', 'from', 'who', 'theirs', 'until', 'should', 'doing', 'most', 'some', 'itself', 'will', 'she', 'further', 'why', 'do', 'there', 'under', 'nor', 'on', 'are', 'while', 'were', 'them', 'no', 'or', 'in', 'having', 'be', 'against', 'out', 'himself', 'this', 'yourselves', 'own', 'but', 'too', 'am', 'again', 'that', 'don', 'is', 'below', 'those', 'a', 'with', 'than', 'my', 'what', 'same', 'i', 'yours', 'by', 'into', 'he', 'now', 'ours', 'an', 'here', 'so', 'between', 'themselves', 'where', 'few', 'had', 'any'}

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\2471722201.py:1: SyntaxWarning: invalid escape sequence '\s'
  with open("data\stopwords.txt", "r", encoding="utf-8") as f:

In [22]:
def preprocessing(document):
    
    try: 
        word_set = set()
        document = nlp(document)
        for word in document:
            lemma = word.lemma_.strip().lower()
        
            if (
                lemma
                and lemma not in stopwords
                and word.is_alpha
                and not word.is_punct
                and not word.is_space
            ):
                word_set.add(lemma)
        return word_set
    except:
        return set()

In [23]:
#abstract_reshape = preprocessing()

abstract["processed"] = abstract.abstract.apply(preprocessing)

C:\Users\Mi\AppData\Local\Temp\ipykernel_30940\3746059958.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abstract["processed"] = abstract.abstract.apply(preprocessing)

In [24]:
abstract

,abstract,processed
0,Congress could do much more to protect America...,"{protect, serve, predatory, americans, congres..."
1,Christina Iverson and Jeff Chen ring in the Ne...,"{ring, year, jeff, iverson, chen, christina, new}"
2,"All year long, Earth passes through streams of...","{meteor, stream, year, shower, cosmic, major, ..."
3,"Never miss an eclipse, a meteor shower, a rock...","{meteor, shower, never, event, space, world, m..."
4,A year full of highs and lows in space just en...,"{year, low, end, month, highlight, space, high..."
...,...,...
16782,"Survivors can get better, but they need help.","{get, help, survivor, need, well}"
16783,While many teams continued to assess the finan...,"{diego, consequence, financial, world, become,..."
16784,Banks have the power to decide whether to let ...,"{overdrawn, whether, gain, account, bank, powe..."
16785,The new category of ‘clean wines’ is an effort...,"{try, seek, clean, healthful, effort, appeal, ..."
16786,The hackers gained more access than the compan...,"{code, company, reveal, email, modify, unable,..."

Jaccard similarity

In [25]:
def jaccard (words1:set, words2:set):
    intersection = words1.intersection(words2)
    union = words1.union(words2) 

    if union == 0:
        return None
    jaccard_sim = round(len(intersection) /len(union), 5)
    return jaccard_sim

words1 = abstract.processed.iloc[10]
words2 = abstract.processed.iloc[10532]
jacsim1 = jaccard(words1, words2)

In [26]:
jacsim1

0.14286

In [27]:
type(abstract)

pandas.core.frame.DataFrame

In [39]:
def jaccard_sim_for_main (df:pd.DataFrame, number_main:int, top_k=5):
    main_abstract = df.processed.iloc[number_main]
    overall_jaccard_for_main = dict()
    for idxr, abstract in enumerate(df.processed):
        jacc_sim = jaccard(main_abstract, abstract)
        overall_jaccard_for_main[idxr] = jacc_sim

    overall_jaccard_for_main = sorted(
    overall_jaccard_for_main.items(),
    key=lambda x: x[1],
    reverse=True
    )[:top_k]
    return overall_jaccard_for_main

In [40]:
jaccard_sim_for_1 = jaccard_sim_for_main(abstract, 10)
jaccard_sim_for_1

[(10, 1.0), (2952, 0.15789), (10532, 0.14286), (2988, 0.10526), (2526, 0.1)]

In [ ]:
def jaccard_total(df:pd.DataFrame):
    for article_idx, article in enumerate(df.processed):
        jaccard_sim_idx = jaccard_sim_for_main(df, article_idx)