In [6]:
import os
os.environ['KAGGLE_USERNAME'] = "anastasiakhromova"
os.environ['KAGGLE_KEY'] = "KGAT_a4177bc6807822bc6d28ff5e23b1caff"
!kaggle datasets download benjaminawd/new-york-times-articles-comments-2020

Dataset URL: https://www.kaggle.com/datasets/benjaminawd/new-york-times-articles-comments-2020
License(s): CC-BY-NC-SA-4.0
Downloading new-york-times-articles-comments-2020.zip to d:\Projects\finding_similar_items\data

  0%|          | 0.00/1.95G [00:00<?, ?B/s]
  0%|          | 1.00M/1.95G [00:00<26:18, 1.32MB/s]
  0%|          | 2.00M/1.95G [00:01<16:28, 2.11MB/s]
  0%|          | 3.00M/1.95G [00:01<18:42, 1.86MB/s]
  0%|          | 4.00M/1.95G [00:01<14:45, 2.36MB/s]
  0%|          | 5.00M/1.95G [00:02<16:47, 2.07MB/s]
  0%|          | 6.00M/1.95G [00:02<14:17, 2.43MB/s]
  0%|          | 7.00M/1.95G [00:03<17:57, 1.93MB/s]
  0%|          | 8.00M/1.95G [00:04<17:46, 1.95MB/s]
  0%|          | 9.00M/1.95G [00:04<17:41, 1.96MB/s]
  1%|          | 10.0M/1.95G [00:05<16:21, 2.12MB/s]
  1%|          | 11.0M/1.95G [00:05<17:43, 1.96MB/s]
  1%|          | 12.0M/1.95G [00:06<15:27, 2.24MB/s]
  1%|          | 13.0M/1.95G [00:06<14:23, 2.41MB/s]
  1%|          | 14.0M/1.95G [00:06<13:10, 2.63MB/s]
  1%|          | 15.0M/1.95G [00:07<12:43, 2.72MB/s]
  1%|          | 16.0M/1.95G [00:07<13:24, 2.58MB/s]
  1%|          | 17.0M/1.95G [00:07<11:19, 3.05MB/s]
  1%|          | 18.0M/1.95G [00:08<14:27, 2.39MB/s]
  1%|          | 19.0M/1.95G [00:08<12:04, 2.86MB/s]
  1%|          | 20.0M/1.95G [00:09<16:47, 2.05MB/s]
  1%|          | 21.0M/1.95G [00:17<1:28:05, 392kB/s]
  1%|          | 22.0M/1.95G [00:17<1:05:23, 527kB/s]
  1%|          | 23.0M/1.95G [00:18<51:49, 665kB/s]
  1%|          | 24.0M/1.95G [00:19<47:17, 728kB/s]
  1%|▏         | 25.0M/1.95G [00:19<36:59, 930kB/s]
  1%|▏         | 26.0M/1.95G [00:20<29:34, 1.16MB/s]
  1%|▏         | 27.0M/1.95G [00:20<24:04, 1.43MB/s]
  1%|▏         | 28.0M/1.95G [00:20<19:56, 1.72MB/s]
  1%|▏         | 29.0M/1.95G [00:21<16:54, 2.03MB/s]
  2%|▏         | 30.0M/1.95G [00:21<13:52, 2.47MB/s]
  2%|▏         | 31.0M/1.95G [00:21<12:05, 2.84MB/s]
  2%|▏         | 32.0M/1.95G [00:21<09:54, 3.46MB/s]
  2%|▏         | 33.0M/1.95G [00:21<08:53, 3.86MB/s]
  2%|▏         | 34.0M/1.95G [00:21<07:37, 4.49MB/s]
  2%|▏         | 35.0M/1.95G [00:22<07:21, 4.66MB/s]
  2%|▏         | 36.0M/1.95G [00:22<07:07, 4.81MB/s]
  2%|▏         | 37.0M/1.95G [00:22<10:23, 3.29MB/s]
  2%|▏         | 38.0M/1.95G [00:23<08:48, 3.88MB/s]
  2%|▏         | 39.0M/1.95G [00:23<08:25, 4.05MB/s]
  2%|▏         | 40.0M/1.95G [00:23<08:41, 3.93MB/s]
  2%|▏         | 41.0M/1.95G [00:24<16:51, 2.02MB/s]
  2%|▏         | 43.0M/1.95G [00:25<11:48, 2.89MB/s]
  2%|▏         | 44.0M/1.95G [00:25<10:01, 3.40MB/s]
  2%|▏         | 45.0M/1.95G [00:25<09:44, 3.50MB/s]
  2%|▏         | 46.0M/1.95G [00:25<09:20, 3.64MB/s]
  2%|▏         | 47.0M/1.95G [00:25<08:07, 4.19MB/s]
  2%|▏         | 48.0M/1.95G [00:26<08:08, 4.18MB/s]
  2%|▏         | 49.0M/1.95G [00:26<07:06, 4.78MB/s]
  3%|▎         | 50.0M/1.95G [00:26<07:35, 4.48MB/s]
  3%|▎         | 51.0M/1.95G [00:26<06:39, 5.10MB/s]
  3%|▎         | 52.0M/1.95G [00:27<07:56, 4.28MB/s]
  3%|▎         | 53.0M/1.95G [00:27<06:53, 4.92MB/s]
  3%|▎         | 54.0M/1.95G [00:27<06:50, 4.96MB/s]
  3%|▎         | 55.0M/1.95G [00:27<07:26, 4.56MB/s]
  3%|▎         | 56.0M/1.95G [00:27<06:52, 4.93MB/s]
  3%|▎         | 57.0M/1.95G [00:28<09:48, 3.45MB/s]
  3%|▎         | 58.0M/1.95G [00:28<10:51, 3.12MB/s]
  3%|▎         | 59.0M/1.95G [00:29<11:15, 3.01MB/s]
  3%|▎         | 60.0M/1.95G [00:29<12:07, 2.79MB/s]
  3%|▎         | 61.0M/1.95G [00:29<11:28, 2.95MB/s]
  3%|▎         | 62.0M/1.95G [00:30<16:04, 2.10MB/s]
  3%|▎         | 63.0M/1.95G [00:31<17:26, 1.93MB/s]
  3%|▎         | 64.0M/1.95G [00:31<15:58, 2.11MB/s]
  3%|▎         | 65.0M/1.95G [00:32<16:29, 2.05MB/s]
  3%|▎         | 66.0M/1.95G [00:32<14:47, 2.28MB/s]
  3%|▎         | 67.0M/1.95G [00:33<13:50, 2.43MB/s]
  3%|▎         | 68.0M/1.95G [00:33<12:56, 2.60MB/s]
  3%|▎         | 69.0M/1.95G [00:33<11:31, 2.92MB/s]
  4%|▎         | 70.0M/1.95G [00:34<12:15, 2.74MB/s]
  4%|▎         | 71.0M/1.95G [00:34<11:20, 2.96MB/s]
  4%|▎         | 72.0M/1.95G [00:34<12:08, 2.77MB/s]
  4%|▎         | 73.0M/1.95G [00:35<13:23, 2.51MB/s]
  4%|▎         | 74.0M/1.95G [00:35<16:10, 2.07MB/s]
  4%|▍         | 75.0M/1.95G [00:36<16:31, 2.03MB/s]
  4%|▍         | 76.0M/1.95G [00:36<15:43, 2.13MB/s]
  4%|▍         | 77.0M/1.95G [00:37<17:57, 1.87MB/s]
  4%|▍         | 78.0M/1.95G [00:37<14:59, 2.23MB/s]
  4%|▍         | 79.0M/1.95G [00:38<14:40, 2.28MB/s]
  4%|▍         | 80.0M/1.95G [00:38<15:02, 2.23MB/s]
  4%|▍         | 81.0M/1.95G [00:39<14:04, 2.37MB/s]
  4%|▍         | 82.0M/1.95G [00:39<12:43, 2.63MB/s]
  4%|▍         | 83.0M/1.95G [00:40<15:11, 2.20MB/s]
  4%|▍         | 84.0M/1.95G [00:40<13:20, 2.50MB/s]
  4%|▍         | 85.0M/1.95G [00:40<12:26, 2.68MB/s]
  4%|▍         | 86.0M/1.95G [00:41<11:58, 2.78MB/s]
  4%|▍         | 87.0M/1.95G [00:41<09:52, 3.37MB/s]
  4%|▍         | 88.0M/1.95G [00:42<13:38, 2.44MB/s]
  5%|▍         | 90.0M/1.95G [00:42<11:27, 2.91MB/s]
  5%|▍         | 91.0M/1.95G [00:42<10:31, 3.16MB/s]
  5%|▍         | 92.0M/1.95G [00:43<09:46, 3.40MB/s]
  5%|▍         | 93.0M/1.95G [00:43<09:52, 3.36MB/s]
  5%|▍         | 94.0M/1.95G [00:44<17:36, 1.89MB/s]
  5%|▍         | 95.0M/1.95G [00:44<14:10, 2.34MB/s]
  5%|▍         | 96.0M/1.95G [00:45<14:15, 2.33MB/s]
  5%|▍         | 97.0M/1.95G [00:45<13:52, 2.39MB/s]
  5%|▍         | 98.0M/1.95G [00:45<12:58, 2.56MB/s]
  5%|▍         | 99.0M/1.95G [00:46<12:10, 2.72MB/s]
  5%|▌         | 100M/1.95G [00:46<11:01, 3.00MB/s]
  5%|▌         | 101M/1.95G [00:46<09:48, 3.37MB/s]
  5%|▌         | 102M/1.95G [00:47<10:53, 3.04MB/s]
  5%|▌         | 103M/1.95G [00:47<09:30, 3.48MB/s]
  5%|▌         | 104M/1.95G [00:47<08:30, 3.88MB/s]
  5%|▌         | 105M/1.95G [00:47<08:41, 3.80MB/s]
  5%|▌         | 106M/1.95G [00:48<07:50, 4.20MB/s]
  5%|▌         | 107M/1.95G [00:48<07:00, 4.71MB/s]
  5%|▌         | 108M/1.95G [00:48<07:14, 4.56MB/s]
  5%|▌         | 109M/1.95G [00:48<06:27, 5.11MB/s]
  6%|▌         | 110M/1.95G [00:48<05:44, 5.74MB/s]
  6%|▌         | 111M/1.95G [00:48<05:30, 5.98MB/s]
  6%|▌         | 112M/1.95G [00:49<05:27, 6.03MB/s]
  6%|▌         | 113M/1.95G [00:50<15:32, 2.12MB/s]
  6%|▌         | 114M/1.95G [00:50<12:24, 2.65MB/s]
  6%|▌         | 115M/1.95G [00:50<11:04, 2.97MB/s]
  6%|▌         | 116M/1.95G [00:51<10:13, 3.21MB/s]
  6%|▌         | 117M/1.95G [00:51<08:56, 3.67MB/s]
  6%|▌         | 118M/1.95G [00:51<10:53, 3.01MB/s]
  6%|▌         | 119M/1.95G [00:51<08:58, 3.65MB/s]
  6%|▌         | 120M/1.95G [00:51<07:43, 4.24MB/s]
  6%|▌         | 121M/1.95G [00:52<07:13, 4.53MB/s]
  6%|▌         | 122M/1.95G [00:52<06:47, 4.82MB/s]
  6%|▌         | 123M/1.95G [00:52<07:30, 4.35MB/s]
  6%|▌         | 124M/1.95G [00:52<06:53, 4.74MB/s]
  6%|▋         | 125M/1.95G [00:52<06:14, 5.23MB/s]
  6%|▋         | 126M/1.95G [00:53<07:37, 4.28MB/s]
  6%|▋         | 127M/1.95G [00:54<11:55, 2.74MB/s]
  6%|▋         | 129M/1.95G [00:54<08:29, 3.84MB/s]
  7%|▋         | 130M/1.95G [00:54<08:18, 3.92MB/s]
  7%|▋         | 131M/1.95G [00:54<07:08, 4.56MB/s]
  7%|▋         | 132M/1.95G [00:55<09:03, 3.59MB/s]
  7%|▋         | 134M/1.95G [00:55<06:37, 4.90MB/s]
  7%|▋         | 135M/1.95G [00:55<06:01, 5.40MB/s]
  7%|▋         | 136M/1.95G [00:55<05:56, 5.46MB/s]
  7%|▋         | 137M/1.95G [00:56<12:39, 2.56MB/s]
  7%|▋         | 138M/1.95G [00:57<11:40, 2.78MB/s]
  7%|▋         | 139M/1.95G [00:57<11:13, 2.89MB/s]
  7%|▋         | 140M/1.95G [00:57<09:24, 3.44MB/s]
  7%|▋         | 141M/1.95G [00:57<07:36, 4.26MB/s]
  7%|▋         | 142M/1.95G [00:57<07:38, 4.23MB/s]
  7%|▋         | 143M/1.95G [00:58<07:21, 4.39MB/s]
  7%|▋         | 144M/1.95G [00:58<08:46, 3.69MB/s]
  7%|▋         | 145M/1.95G [00:58<09:23, 3.44MB/s]
  7%|▋         | 146M/1.95G [00:59<12:48, 2.52MB/s]
  7%|▋         | 147M/1.95G [00:59<11:18, 2.85MB/s]
  7%|▋         | 148M/1.95G [00:59<09:10, 3.51MB/s]
  7%|▋         | 149M/1.95G [01:00<11:28, 2.81MB/s]
  8%|▊         | 150M/1.95G [01:00<11:19, 2.85MB/s]
  8%|▊         | 151M/1.95G [01:01<11:42, 2.75MB/s]
  8%|▊         | 152M/1.95G [01:02<16:45, 1.92MB/s]
  8%|▊         | 153M/1.95G [01:02<17:37, 1.83MB/s]
  8%|▊         | 154M/1.95G [01:03<17:04, 1.88MB/s]
  8%|▊         | 155M/1.95G [01:03<16:25, 1.96MB/s]
  8%|▊         | 156M/1.95G [01:04<14:57, 2.15MB/s]
  8%|▊         | 157M/1.95G [01:04<15:37, 2.06MB/s]
  8%|▊         | 158M/1.95G [01:05<14:49, 2.16MB/s]
  8%|▊         | 159M/1.95G [01:05<14:36, 2.20MB/s]
  8%|▊         | 160M/1.95G [01:05<13:41, 2.34MB/s]
  8%|▊         | 161M/1.95G [01:06<13:35, 2.36MB/s]
  8%|▊         | 162M/1.95G [01:06<13:52, 2.31MB/s]
  8%|▊         | 163M/1.95G [01:07<15:25, 2.08MB/s]
  8%|▊         | 164M/1.95G [01:08<20:48, 1.54MB/s]
  8%|▊         | 165M/1.95G [01:08<16:54, 1.89MB/s]
  8%|▊         | 166M/1.95G [01:09<14:18, 2.23MB/s]
  8%|▊         | 167M/1.95G [01:09<12:30, 2.55MB/s]
  8%|▊         | 168M/1.95G [01:09<11:54, 2.68MB/s]
  8%|▊         | 169M/1.95G [01:09<10:22, 3.08MB/s]
  9%|▊         | 170M/1.95G [01:10<09:24, 3.39MB/s]
  9%|▊         | 171M/1.95G [01:10<08:27, 3.77MB/s]
  9%|▊         | 172M/1.95G [01:10<08:27, 3.77MB/s]
  9%|▊         | 173M/1.95G [01:11<12:38, 2.52MB/s]
  9%|▊         | 174M/1.95G [01:11<11:55, 2.67MB/s]
  9%|▉         | 175M/1.95G [01:12<15:12, 2.09MB/s]
  9%|▉         | 176M/1.95G [01:12<12:01, 2.64MB/s]
  9%|▉         | 177M/1.95G [01:13<12:16, 2.59MB/s]
  9%|▉         | 178M/1.95G [01:13<11:41, 2.71MB/s]
  9%|▉         | 179M/1.95G [01:13<10:28, 3.03MB/s]
  9%|▉         | 180M/1.95G [01:14<13:01, 2.43MB/s]
  9%|▉         | 181M/1.95G [01:14<11:16, 2.81MB/s]
  9%|▉         | 182M/1.95G [01:14<10:06, 3.13MB/s]
  9%|▉         | 183M/1.95G [01:15<09:19, 3.39MB/s]
  9%|▉         | 184M/1.95G [01:15<08:34, 3.69MB/s]
  9%|▉         | 185M/1.95G [01:15<08:22, 3.78MB/s]
  9%|▉         | 186M/1.95G [01:15<07:20, 4.31MB/s]
  9%|▉         | 187M/1.95G [01:15<07:27, 4.23MB/s]
  9%|▉         | 188M/1.95G [01:16<07:01, 4.49MB/s]
  9%|▉         | 189M/1.95G [01:16<06:03, 5.20MB/s]
 10%|▉         | 190M/1.95G [01:16<06:40, 4.72MB/s]
 10%|▉         | 191M/1.95G [01:16<06:11, 5.09MB/s]
 10%|▉         | 192M/1.95G [01:16<06:26, 4.89MB/s]
 10%|▉         | 193M/1.95G [01:17<10:17, 3.06MB/s]
 10%|▉         | 194M/1.95G [01:18<11:49, 2.66MB/s]
 10%|▉         | 195M/1.95G [01:18<09:53, 3.18MB/s]
 10%|▉         | 196M/1.95G [01:18<09:20, 3.36MB/s]
 10%|▉         | 197M/1.95G [01:18<08:55, 3.52MB/s]
 10%|▉         | 198M/1.95G [01:19<07:37, 4.12MB/s]
 10%|▉         | 199M/1.95G [01:19<07:50, 4.01MB/s]
 10%|█         | 200M/1.95G [01:19<09:48, 3.20MB/s]
 10%|█         | 201M/1.95G [01:19<08:36, 3.64MB/s]
 10%|█         | 202M/1.95G [01:20<07:43, 4.06MB/s]
 10%|█         | 203M/1.95G [01:20<07:21, 4.25MB/s]
 10%|█         | 204M/1.95G [01:20<06:35, 4.75MB/s]
 10%|█         | 205M/1.95G [01:20<05:59, 5.21MB/s]
 10%|█         | 206M/1.95G [01:20<05:50, 5.34MB/s]
 10%|█         | 207M/1.95G [01:21<05:48, 5.37MB/s]
 10%|█         | 208M/1.95G [01:21<05:45, 5.42MB/s]
 10%|█         | 209M/1.95G [01:21<06:23, 4.89MB/s]
 11%|█         | 210M/1.95G [01:21<05:40, 5.49MB/s]
 11%|█         | 211M/1.95G [01:21<05:45, 5.41MB/s]
 11%|█         | 212M/1.95G [01:21<05:05, 6.12MB/s]
 11%|█         | 213M/1.95G [01:22<05:07, 6.07MB/s]
 11%|█         | 214M/1.95G [01:22<05:29, 5.67MB/s]
 11%|█         | 215M/1.95G [01:22<04:56, 6.30MB/s]
 11%|█         | 216M/1.95G [01:22<05:32, 5.60MB/s]
 11%|█         | 217M/1.95G [01:22<05:51, 5.30MB/s]
 11%|█         | 218M/1.95G [01:23<05:17, 5.86MB/s]
 11%|█         | 219M/1.95G [01:23<05:54, 5.25MB/s]
 11%|█         | 220M/1.95G [01:23<05:44, 5.40MB/s]
 11%|█         | 221M/1.95G [01:23<06:28, 4.79MB/s]
 11%|█         | 222M/1.95G [01:23<05:36, 5.53MB/s]
 11%|█         | 223M/1.95G [01:24<05:30, 5.62MB/s]
 11%|█         | 224M/1.95G [01:25<17:15, 1.79MB/s]
 11%|█▏        | 226M/1.95G [01:26<16:22, 1.89MB/s]
 11%|█▏        | 227M/1.95G [01:27<15:06, 2.04MB/s]
 11%|█▏        | 228M/1.95G [01:27<13:53, 2.22MB/s]
 11%|█▏        | 229M/1.95G [01:27<12:58, 2.38MB/s]
 12%|█▏        | 230M/1.95G [01:28<11:35, 2.66MB/s]
 12%|█▏        | 231M/1.95G [01:28<10:28, 2.94MB/s]
 12%|█▏        | 232M/1.95G [01:28<09:22, 3.29MB/s]
 12%|█▏        | 233M/1.95G [01:28<08:16, 3.72MB/s]
 12%|█▏        | 234M/1.95G [01:28<07:34, 4.06MB/s]
 12%|█▏        | 235M/1.95G [01:29<07:47, 3.95MB/s]
 12%|█▏        | 236M/1.95G [01:29<09:47, 3.14MB/s]
 12%|█▏        | 237M/1.95G [01:29<08:11, 3.75MB/s]
 12%|█▏        | 238M/1.95G [01:29<07:12, 4.25MB/s]
 12%|█▏        | 239M/1.95G [01:30<06:38, 4.62MB/s]
 12%|█▏        | 240M/1.95G [01:30<07:04, 4.34MB/s]
 12%|█▏        | 241M/1.95G [01:30<06:26, 4.75MB/s]
 12%|█▏        | 242M/1.95G [01:30<06:04, 5.04MB/s]
 12%|█▏        | 243M/1.95G [01:30<05:35, 5.48MB/s]
 12%|█▏        | 244M/1.95G [01:31<06:30, 4.70MB/s]
 12%|█▏        | 245M/1.95G [01:31<07:29, 4.08MB/s]
 12%|█▏        | 247M/1.95G [01:32<06:48, 4.49MB/s]
 12%|█▏        | 248M/1.95G [01:33<12:37, 2.42MB/s]
 13%|█▎        | 250M/1.95G [01:33<08:58, 3.40MB/s]
 13%|█▎        | 251M/1.95G [01:33<09:18, 3.28MB/s]
 13%|█▎        | 252M/1.95G [01:33<09:19, 3.26MB/s]
 13%|█▎        | 253M/1.95G [01:34<09:58, 3.05MB/s]
 13%|█▎        | 254M/1.95G [01:34<09:49, 3.10MB/s]
 13%|█▎        | 255M/1.95G [01:35<09:39, 3.15MB/s]
 13%|█▎        | 256M/1.95G [01:35<09:53, 3.07MB/s]
 13%|█▎        | 257M/1.95G [01:35<08:48, 3.45MB/s]
 13%|█▎        | 258M/1.95G [01:36<10:12, 2.97MB/s]
 13%|█▎        | 259M/1.95G [01:36<08:23, 3.61MB/s]
 13%|█▎        | 260M/1.95G [01:36<09:06, 3.33MB/s]
 13%|█▎        | 261M/1.95G [01:36<09:11, 3.30MB/s]
 13%|█▎        | 262M/1.95G [01:37<08:52, 3.41MB/s]
 13%|█▎        | 263M/1.95G [01:37<12:33, 2.41MB/s]
 13%|█▎        | 264M/1.95G [01:38<10:37, 2.85MB/s]
 13%|█▎        | 265M/1.95G [01:38<09:51, 3.07MB/s]
 13%|█▎        | 266M/1.95G [01:38<10:03, 3.00MB/s]
 13%|█▎        | 267M/1.95G [01:38<08:42, 3.47MB/s]
 13%|█▎        | 268M/1.95G [01:39<09:04, 3.32MB/s]
 13%|█▎        | 269M/1.95G [01:39<09:03, 3.33MB/s]
 14%|█▎        | 270M/1.95G [01:39<09:09, 3.29MB/s]
 14%|█▎        | 271M/1.95G [01:40<10:20, 2.91MB/s]
 14%|█▎        | 272M/1.95G [01:40<09:13, 3.26MB/s]
 14%|█▎        | 273M/1.95G [01:41<09:59, 3.01MB/s]
 14%|█▎        | 274M/1.95G [01:41<09:47, 3.07MB/s]
 14%|█▍        | 275M/1.95G [01:41<08:33, 3.51MB/s]
 14%|█▍        | 276M/1.95G [01:42<11:45, 2.55MB/s]
 14%|█▍        | 277M/1.95G [01:43<17:03, 1.76MB/s]
 14%|█▍        | 278M/1.95G [01:43<14:11, 2.11MB/s]
 14%|█▍        | 279M/1.95G [01:46<34:59, 857kB/s]
 14%|█▍        | 280M/1.95G [01:46<27:32, 1.09MB/s]
 14%|█▍        | 281M/1.95G [01:47<21:49, 1.37MB/s]
 14%|█▍        | 282M/1.95G [01:47<18:55, 1.58MB/s]
 14%|█▍        | 283M/1.95G [01:47<15:08, 1.98MB/s]
 14%|█▍        | 284M/1.95G [01:48<12:32, 2.38MB/s]
 14%|█▍        | 285M/1.95G [01:48<10:04, 2.97MB/s]
 14%|█▍        | 286M/1.95G [01:48<08:21, 3.57MB/s]
 14%|█▍        | 287M/1.95G [01:48<07:15, 4.11MB/s]
 14%|█▍        | 288M/1.95G [01:48<06:36, 4.52MB/s]
 14%|█▍        | 289M/1.95G [01:48<05:42, 5.22MB/s]
 15%|█▍        | 290M/1.95G [01:48<05:10, 5.75MB/s]
 15%|█▍        | 291M/1.95G [01:49<05:32, 5.37MB/s]
 15%|█▍        | 292M/1.95G [01:49<04:58, 5.98MB/s]
 15%|█▍        | 293M/1.95G [01:49<04:49, 6.16MB/s]
 15%|█▍        | 294M/1.95G [01:49<06:36, 4.50MB/s]
 15%|█▍        | 297M/1.95G [01:50<03:49, 7.76MB/s]
 15%|█▍        | 298M/1.95G [01:50<03:57, 7.50MB/s]
 15%|█▍        | 299M/1.95G [01:50<03:44, 7.91MB/s]
 15%|█▌        | 300M/1.95G [01:50<04:16, 6.93MB/s]
 15%|█▌        | 301M/1.95G [01:50<04:15, 6.95MB/s]
 15%|█▌        | 302M/1.95G [01:50<03:59, 7.41MB/s]
 15%|█▌        | 304M/1.95G [01:52<11:15, 2.62MB/s]
 15%|█▌        | 306M/1.95G [01:52<08:28, 3.48MB/s]
 15%|█▌        | 307M/1.95G [01:52<07:34, 3.89MB/s]
 15%|█▌        | 308M/1.95G [01:52<06:38, 4.44MB/s]
 15%|█▌        | 309M/1.95G [01:52<06:23, 4.61MB/s]
 16%|█▌        | 310M/1.95G [01:53<09:37, 3.06MB/s]
 16%|█▌        | 311M/1.95G [01:57<32:56, 893kB/s]
 16%|█▌        | 312M/1.95G [01:58<32:49, 896kB/s]
 16%|█▌        | 313M/1.95G [01:58<26:16, 1.12MB/s]
 16%|█▌        | 314M/1.95G [01:58<22:00, 1.33MB/s]
 16%|█▌        | 315M/1.95G [01:59<19:33, 1.50MB/s]
 16%|█▌        | 316M/1.95G [01:59<17:18, 1.69MB/s]
 16%|█▌        | 317M/1.95G [02:00<15:28, 1.90MB/s]
 16%|█▌        | 318M/1.95G [02:00<14:51, 1.97MB/s]
 16%|█▌        | 319M/1.95G [02:01<12:32, 2.34MB/s]
 16%|█▌        | 320M/1.95G [02:01<15:17, 1.91MB/s]
 16%|█▌        | 321M/1.95G [02:01<12:18, 2.38MB/s]
 16%|█▌        | 322M/1.95G [02:02<14:28, 2.02MB/s]
 16%|█▌        | 323M/1.95G [02:03<13:26, 2.17MB/s]
 16%|█▌        | 324M/1.95G [02:03<13:51, 2.11MB/s]
 16%|█▋        | 325M/1.95G [02:03<12:45, 2.29MB/s]
 16%|█▋        | 326M/1.95G [02:04<14:17, 2.04MB/s]
 16%|█▋        | 327M/1.95G [02:04<11:04, 2.63MB/s]
 16%|█▋        | 328M/1.95G [02:05<12:36, 2.31MB/s]
 16%|█▋        | 329M/1.95G [02:05<12:54, 2.26MB/s]
 17%|█▋        | 330M/1.95G [02:06<11:10, 2.60MB/s]
 17%|█▋        | 331M/1.95G [02:06<10:38, 2.73MB/s]
 17%|█▋        | 332M/1.95G [02:06<11:47, 2.46MB/s]
 17%|█▋        | 333M/1.95G [02:07<13:23, 2.17MB/s]
 17%|█▋        | 334M/1.95G [02:07<12:33, 2.31MB/s]
 17%|█▋        | 335M/1.95G [02:08<16:46, 1.73MB/s]
 17%|█▋        | 336M/1.95G [02:09<15:16, 1.90MB/s]
 17%|█▋        | 337M/1.95G [02:09<13:04, 2.22MB/s]
 17%|█▋        | 338M/1.95G [02:09<11:00, 2.63MB/s]
 17%|█▋        | 339M/1.95G [02:10<09:11, 3.15MB/s]
 17%|█▋        | 340M/1.95G [02:10<07:46, 3.72MB/s]
 17%|█▋        | 341M/1.95G [02:10<06:59, 4.14MB/s]
 17%|█▋        | 342M/1.95G [02:10<06:30, 4.44MB/s]
 17%|█▋        | 343M/1.95G [02:10<05:37, 5.13MB/s]
 17%|█▋        | 344M/1.95G [02:10<04:54, 5.88MB/s]
 17%|█▋        | 345M/1.95G [02:11<05:36, 5.14MB/s]
 17%|█▋        | 346M/1.95G [02:11<05:10, 5.56MB/s]
 17%|█▋        | 347M/1.95G [02:11<05:36, 5.13MB/s]
 17%|█▋        | 349M/1.95G [02:11<04:22, 6.57MB/s]
 18%|█▊        | 350M/1.95G [02:11<04:17, 6.70MB/s]
 18%|█▊        | 352M/1.95G [02:12<03:52, 7.42MB/s]
 18%|█▊        | 353M/1.95G [02:12<03:54, 7.35MB/s]
 18%|█▊        | 354M/1.95G [02:12<04:16, 6.71MB/s]
 18%|█▊        | 355M/1.95G [02:12<03:56, 7.27MB/s]
 18%|█▊        | 356M/1.95G [02:12<03:45, 7.63MB/s]
 18%|█▊        | 357M/1.95G [02:12<03:47, 7.56MB/s]
 18%|█▊        | 358M/1.95G [02:12<03:50, 7.45MB/s]
 18%|█▊        | 359M/1.95G [02:14<17:29, 1.63MB/s]
 18%|█▊        | 360M/1.95G [02:15<14:35, 1.96MB/s]
 18%|█▊        | 361M/1.95G [02:15<12:03, 2.37MB/s]
 18%|█▊        | 362M/1.95G [02:15<10:43, 2.66MB/s]
 18%|█▊        | 363M/1.95G [02:16<16:24, 1.74MB/s]
 18%|█▊        | 364M/1.95G [02:17<14:52, 1.92MB/s]
 18%|█▊        | 365M/1.95G [02:17<12:34, 2.26MB/s]
 18%|█▊        | 366M/1.95G [02:18<20:13, 1.41MB/s]
 18%|█▊        | 367M/1.95G [02:19<21:04, 1.35MB/s]
 18%|█▊        | 368M/1.95G [02:20<19:17, 1.47MB/s]
 19%|█▊        | 369M/1.95G [02:20<18:51, 1.51MB/s]
 19%|█▊        | 370M/1.95G [02:21<17:58, 1.58MB/s]
 19%|█▊        | 371M/1.95G [02:22<24:13, 1.17MB/s]
 19%|█▊        | 372M/1.95G [02:24<31:14, 908kB/s]
 19%|█▊        | 373M/1.95G [02:25<26:54, 1.05MB/s]
 19%|█▉        | 374M/1.95G [02:25<23:03, 1.23MB/s]
 19%|█▉        | 375M/1.95G [02:26<21:33, 1.31MB/s]
 19%|█▉        | 376M/1.95G [02:26<18:59, 1.49MB/s]
 19%|█▉        | 377M/1.95G [02:27<19:19, 1.46MB/s]
 19%|█▉        | 378M/1.95G [02:28<16:04, 1.76MB/s]
 19%|█▉        | 379M/1.95G [02:28<16:08, 1.75MB/s]
 19%|█▉        | 380M/1.95G [02:28<14:16, 1.98MB/s]
 19%|█▉        | 381M/1.95G [02:29<13:18, 2.12MB/s]
 19%|█▉        | 382M/1.95G [02:29<12:18, 2.29MB/s]
 19%|█▉        | 383M/1.95G [02:30<10:35, 2.66MB/s]
 19%|█▉        | 384M/1.95G [02:30<10:31, 2.67MB/s]
 19%|█▉        | 385M/1.95G [02:30<10:51, 2.59MB/s]
 19%|█▉        | 386M/1.95G [02:31<10:04, 2.79MB/s]
 19%|█▉        | 387M/1.95G [02:32<15:31, 1.81MB/s]
 19%|█▉        | 388M/1.95G [02:32<12:51, 2.18MB/s]
 20%|█▉        | 389M/1.95G [02:32<13:17, 2.11MB/s]
 20%|█▉        | 390M/1.95G [02:33<12:47, 2.19MB/s]
 20%|█▉        | 391M/1.95G [02:33<11:59, 2.34MB/s]
 20%|█▉        | 392M/1.95G [02:34<12:09, 2.30MB/s]
 20%|█▉        | 393M/1.95G [02:34<10:32, 2.65MB/s]
 20%|█▉        | 394M/1.95G [02:34<09:59, 2.80MB/s]
 20%|█▉        | 395M/1.95G [02:35<10:46, 2.59MB/s]

In [9]:
import pandas as pd 
import numpy as np

# EDA

In [21]:
data_path = "D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020"

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Mi\AppData\Local\Temp\ipykernel_20400\2168738046.py:1: SyntaxWarning: invalid escape sequence '\P'
  data_path = "D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020"

In [23]:
test = pd.read_csv(data_path+'\\test.csv')
test

,newsdesk,section,subsection,material,headline,abstract,keywords,word_count,pub_date,is_popular,uniqueID
0,OpEd,Opinion,NaN,Op-Ed,Anyone Else Want to See Trump ‘Shut Up’?,Our president as a terrible toddler.,"['Presidential Election of 2020', 'Biden, Jose...",925,2020-10-01 00:05:51+00:00,1,nyt://article/e467c2ae-2df3-5836-a6ca-b23d0d33...
1,OpEd,Opinion,NaN,Op-Ed,Trump Calls on Extremists to ‘Stand By’,"Instead of condemning violent groups, the pres...","['Presidential Election of 2020', 'United Stat...",902,2020-10-01 00:43:28+00:00,1,nyt://article/9a7ef9e0-1334-56b2-a7f1-288c4887...
2,OpEd,Opinion,NaN,Op-Ed,"Can Mike Espy Make History, Again?",If the Democratic Party claims to value Black ...,"['Black People', 'Blacks', 'Presidential Elect...",1412,2020-10-01 00:45:17+00:00,1,nyt://article/4bb2b763-0088-5e10-b204-19e404f7...
3,Games,Crosswords & Games,NaN,News,In Which Rikishi Wear Mawashi,Adam Fromm is on the line.,['Crossword Puzzles'],849,2020-10-01 02:00:05+00:00,1,nyt://article/0d96205f-edb8-5f1f-8c44-1ddf6ed5...
4,Sports,Sports,Pro Football,News,N.F.L. Week 4 Predictions: Our Picks Against t...,Tom Brady and the Buccaneers are building mome...,"['Football', 'New England Patriots', 'Kansas C...",2690,2020-10-01 04:01:16+00:00,0,nyt://article/afc8295b-3c22-5a5f-9539-3f77b7b8...
...,...,...,...,...,...,...,...,...,...,...,...
3990,Editorial,Opinion,NaN,Op-Ed,What It Takes to Heal From Covid-19,"Survivors can get better, but they need help.","['Chronic Condition (Health)', 'Coronavirus (2...",1002,2020-12-31 15:27:47+00:00,1,nyt://article/e8adbb75-a8b3-5a8c-886b-b9c1195f...
3991,Sports,Sports,Baseball,News,Padres Jolt M.L.B. With Bold Moves to Set Up W...,While many teams continued to assess the finan...,"['San Diego Padres', 'Major League Baseball', ...",1100,2020-12-31 15:47:44+00:00,0,nyt://article/1f11417d-2c57-51b9-b75d-8f67f0a9...
3992,Business,Business Day,NaN,News,"Their Finances Ravaged, Customers Fear Banks W...",Banks have the power to decide whether to let ...,"['Banking and Financial Institutions', 'Corona...",1429,2020-12-31 16:21:40+00:00,1,nyt://article/c4b9edab-bdde-5d81-b496-06fedb52...
3993,Dining,Food,"Wine, Beer & Cocktails",News,Should Wine Be Among Your Health Resolutions?,The new category of ‘clean wines’ is an effort...,"['Wines', 'Grapes', 'Diet and Nutrition', 'Dia...",1307,2020-12-31 17:28:11+00:00,1,nyt://article/efcaf652-ffad-5b4e-9f17-4fd9aff5...
3994,Business,Technology,NaN,News,Microsoft Says Russian Hackers Viewed Some of ...,The hackers gained more access than the compan...,"['Microsoft Corp', 'US Federal Government Data...",340,2020-12-31 18:02:02+00:00,1,nyt://article/12048b2b-62e3-5bed-8c77-483a4299...

In [ ]:
git init
git add .
git commit -m "initial commit"

In [24]:
df_main = pd.read_csv('D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020\\nyt-articles-2020.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Mi\AppData\Local\Temp\ipykernel_20400\3702147964.py:1: SyntaxWarning: invalid escape sequence '\P'
  df_main = pd.read_csv('D:\Projects\\finding_similar_items\data\\new-york-times-articles-comments-2020\\nyt-articles-2020.csv')

In [27]:
abstract = df_main[['abstract']]

In [33]:
for a in abstract.abstract[:5]:
    print(a)

Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.
Christina Iverson and Jeff Chen ring in the New Year.
All year long, Earth passes through streams of cosmic debris. Here’s a list of major meteor showers and how to spot one.
Never miss an eclipse, a meteor shower, a rocket launch or any other astronomical and space event that's out of this world.
A year full of highs and lows in space just ended, and the 12 months to come  will be full of new highlights in orbit and beyond.

## Tokenization

In [37]:
!pip install spacy 
import spacy

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.32.0 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.

Collecting spacy
  Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp312-cp312-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (4.66.4)
Requirement already satisfied: numpy>=1.19.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.32.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: jinja2 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\mi\anaconda3\lib\site-packages (from spacy) (69.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\mi\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\mi\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\mi\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.4.22)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in c:\users\mi\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting click>=8.2.1 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\mi\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in c:\users\mi\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.27.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mi\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: anyio in c:\users\mi\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\users\mi\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.2)
Requirement already satisfied: sniffio in c:\users\mi\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\mi\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\mi\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mi\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\mi\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB 32.8 kB/s eta 0:07:14
   ---------------------------------------- 0.0/14.2 MB 32.8 kB/s eta 0:07:14
   ---------------------------------------- 0.0/14.2 MB 32.8 kB/s eta 0:07:14
   ---------------------------------------- 0.0/14.2 MB 32.8 kB/s eta 0:07:14
   ---------------------------------------- 0.0/14.2 MB 38.5 kB/s eta 0:06:09
   ---------------------------------------- 0.0/14.2 MB 38.5 kB/s eta 0:06:09
   ---------------------------------------- 0.0/14.2 MB 38.5 kB/s eta 0:06:09
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 54.6 kB/s eta 0:04:20
   ---------------------------------------- 0.1/14.2 MB 48.5 kB/s eta 0:04:52
   ---------------------------------------- 0.1/14.2 MB 48.5 kB/s eta 0:04:52
   ---------------------------------------- 0.1/14.2 MB 48.5 kB/s eta 0:04:52
   ---------------------------------------- 0.1/14.2 MB 48.5 kB/s eta 0:04:52
   ---------------------------------------- 0.1/14.2 MB 48.5 kB/s eta 0:04:52
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 56.4 kB/s eta 0:04:11
   ---------------------------------------- 0.1/14.2 MB 41.8 kB/s eta 0:05:38
   ---------------------------------------- 0.1/14.2 MB 41.8 kB/s eta 0:05:38
   ---------------------------------------- 0.1/14.2 MB 41.8 kB/s eta 0:05:38
   ---------------------------------------- 0.1/14.2 MB 41.8 kB/s eta 0:05:38
   ---------------------------------------- 0.1/14.2 MB 41.8 kB/s eta 0:05:38
   ---------------------------------------- 0.1/14.2 MB 41.8 kB/s eta 0:05:38
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.3 kB/s eta 0:05:12
   ---------------------------------------- 0.1/14.2 MB 45.1 kB/s eta 0:05:13
   ---------------------------------------- 0.1/14.2 MB 45.1 kB/s eta 0:05:13
   ---------------------------------------- 0.1/14.2 MB 45.1 kB/s eta 0:05:13
   ---------------------------------------- 0.1/14.2 MB 45.1 kB/s eta 0:05:13
   ---------------------------------------- 0.1/14.2 MB 45.1 kB/s eta 0:05:13
   ---------------------------------------- 0.2/14.2 MB 45.0 kB/s eta 0:05:13
   ---------------------------------------- 0.2/14.2 MB 45.0 kB/s eta 0:05:13
   ---------------------------------------- 0.2/14.2 MB 45.0 kB/s eta 0:05:13
   ---------------------------------------- 0.2/14.2 MB 45.0 kB/s eta 0:05:13
   ---------------------------------------- 0.2/14.2 MB 45.0 kB/s eta 0:05:13
   ---------------------------------------- 0.2/14.2 MB 47.9 kB/s eta 0:04:54
   ---------------------------------------- 0.2/14.2 MB 47.9 kB/s eta 0:04:54
   ---------------------------------------- 0.2/14.2 MB 47.9 kB/s eta 0:04:54
   ---------------------------------------- 0.2/14.2 MB 47.9 kB/s eta 0:04:54
   ---------------------------------------- 0.2/14.2 MB 47.9 kB/s eta 0:04:54
    --------------------------------------- 0.2/14.2 MB 47.6 kB/s eta 0:04:55
    --------------------------------------- 0.2/14.2 MB 47.6 kB/s eta 0:04:55
    --------------------------------------- 0.2/14.2 MB 47.6 kB/s eta 0:04:55
    --------------------------------------- 0.2/14.2 MB 47.6 kB/s eta 0:04:55
    --------------------------------------- 0.2/14.2 MB 47.6 kB/s eta 0:04:55
    --------------------------------------- 0.2/14.2 MB 47.6 kB/s eta 0:04:55
    --------------------------------------- 0.2/14.2 MB 49.6 kB/s eta 0:04:43
    --------------------------------------- 0.2/14.2 MB 49.6 kB/s eta 0:04:43
    --------------------------------------- 0.2/14.2 MB 49.6 kB/s eta 0:04:43
    --------------------------------------- 0.2/14.2 MB 52.5 kB/s eta 0:04:27
    --------------------------------------- 0.2/14.2 MB 52.5 kB/s eta 0:04:27
    --------------------------------------- 0.2/14.2 MB 52.5 kB/s eta 0:04:27
    --------------------------------------- 0.2/14.2 MB 52.5 kB/s eta 0:04:27
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.2/14.2 MB 52.6 kB/s eta 0:04:26
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 52.1 kB/s eta 0:04:29
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 50.9 kB/s eta 0:04:35
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 49.0 kB/s eta 0:04:45
    --------------------------------------- 0.3/14.2 MB 46.9 kB/s eta 0:04:57
    --------------------------------------- 0.3/14.2 MB 46.9 kB/s eta 0:04:57
    --------------------------------------- 0.3/14.2 MB 46.9 kB/s eta 0:04:57
    --------------------------------------- 0.3/14.2 MB 46.9 kB/s eta 0:04:57
    --------------------------------------- 0.3/14.2 MB 46.9 kB/s eta 0:04:57
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 46.8 kB/s eta 0:04:58
    --------------------------------------- 0.3/14.2 MB 47.7 kB/s eta 0:04:52
    --------------------------------------- 0.3/14.2 MB 47.7 kB/s eta 0:04:52
    --------------------------------------- 0.3/14.2 MB 47.7 kB/s eta 0:04:52
    --------------------------------------- 0.3/14.2 MB 47.7 kB/s eta 0:04:52
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
    --------------------------------------- 0.3/14.2 MB 48.0 kB/s eta 0:04:50
   - -------------------------------------- 0.4/14.2 MB 43.4 kB/s eta 0:05:20
   - -------------------------------------- 0.4/14.2 MB 43.4 kB/s eta 0:05:20

In [38]:
import spacy

In [39]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\mi\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\mi\anaconda3\lib\site-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in c:\users\mi\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mi\anaconda3\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\mi\anaconda3\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in c:\users\mi\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [44]:
import sys
!{sys.executable} -m pip install spacy
!{sys.executable} -m spacy download en_core_web_sm

Requirement already satisfied: spacy in c:\users\mi\anaconda3\lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (4.66.4)
Requirement already satisfied: numpy>=1.19.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.32.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: jinja2 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\mi\anaconda3\lib\site-packages (from spacy) (69.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\mi\anaconda3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\mi\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\mi\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\mi\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mi\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.4.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\mi\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\mi\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\mi\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\mi\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\mi\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\mi\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\mi\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\mi\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in c:\users\mi\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.27.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mi\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: anyio in c:\users\mi\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\users\mi\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.2)
Requirement already satisfied: sniffio in c:\users\mi\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\mi\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\mi\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mi\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\mi\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB 1.3 MB/s eta 0:00:10
     --------------------------------------- 0.0/12.8 MB 487.6 kB/s eta 0:00:27
     --------------------------------------- 0.1/12.8 MB 465.5 kB/s eta 0:00:28
     --------------------------------------- 0.1/12.8 MB 774.0 kB/s eta 0:00:17
      -------------------------------------- 0.2/12.8 MB 981.9 kB/s eta 0:00:13
      --------------------------------------- 0.2/12.8 MB 1.0 MB/s eta 0:00:13
      --------------------------------------- 0.2/12.8 MB 1.0 MB/s eta 0:00:13
      --------------------------------------- 0.2/12.8 MB 1.0 MB/s eta 0:00:13
     - ------------------------------------- 0.3/12.8 MB 805.1 kB/s eta 0:00:16
     - ------------------------------------- 0.3/12.8 MB 805.1 kB/s eta 0:00:16
     - ------------------------------------- 0.3/12.8 MB 805.1 kB/s eta 0:00:16
     - ------------------------------------- 0.4/12.8 MB 712.2 kB/s eta 0:00:18
     - ------------------------------------- 0.4/12.8 MB 689.7 kB/s eta 0:00:18
     - ------------------------------------- 0.4/12.8 MB 689.7 kB/s eta 0:00:18
     - ------------------------------------- 0.4/12.8 MB 595.3 kB/s eta 0:00:21
     - ------------------------------------- 0.5/12.8 MB 625.5 kB/s eta 0:00:20
     - ------------------------------------- 0.5/12.8 MB 601.6 kB/s eta 0:00:21
     - ------------------------------------- 0.5/12.8 MB 580.6 kB/s eta 0:00:22
     - ------------------------------------- 0.5/12.8 MB 561.7 kB/s eta 0:00:22
     - ------------------------------------- 0.5/12.8 MB 561.7 kB/s eta 0:00:22
     - ------------------------------------- 0.5/12.8 MB 545.8 kB/s eta 0:00:23
     - ------------------------------------- 0.5/12.8 MB 522.2 kB/s eta 0:00:24
     - ------------------------------------- 0.6/12.8 MB 510.6 kB/s eta 0:00:24
     - ------------------------------------- 0.6/12.8 MB 510.6 kB/s eta 0:00:24
     - ------------------------------------- 0.6/12.8 MB 510.6 kB/s eta 0:00:24
     - ------------------------------------- 0.6/12.8 MB 510.6 kB/s eta 0:00:24
     - ------------------------------------- 0.6/12.8 MB 464.3 kB/s eta 0:00:27
     - ------------------------------------- 0.6/12.8 MB 463.3 kB/s eta 0:00:27
     - ------------------------------------- 0.6/12.8 MB 463.3 kB/s eta 0:00:27
     - ------------------------------------- 0.6/12.8 MB 444.2 kB/s eta 0:00:28
     - ------------------------------------- 0.6/12.8 MB 444.2 kB/s eta 0:00:28
     - ------------------------------------- 0.6/12.8 MB 420.6 kB/s eta 0:00:29
     - ------------------------------------- 0.7/12.8 MB 434.4 kB/s eta 0:00:28
     - ------------------------------------- 0.7/12.8 MB 434.4 kB/s eta 0:00:28
     -- ------------------------------------ 0.7/12.8 MB 411.1 kB/s eta 0:00:30
     -- ------------------------------------ 0.7/12.8 MB 411.1 kB/s eta 0:00:30
     -- ------------------------------------ 0.7/12.8 MB 393.2 kB/s eta 0:00:31
     -- ------------------------------------ 0.7/12.8 MB 393.2 kB/s eta 0:00:31
     -- ------------------------------------ 0.7/12.8 MB 393.2 kB/s eta 0:00:31
     -- ------------------------------------ 0.7/12.8 MB 372.1 kB/s eta 0:00:33
     -- ------------------------------------ 0.7/12.8 MB 372.1 kB/s eta 0:00:33
     -- ------------------------------------ 0.7/12.8 MB 372.1 kB/s eta 0:00:33
     -- ------------------------------------ 0.7/12.8 MB 358.8 kB/s eta 0:00:34
     -- ------------------------------------ 0.7/12.8 MB 358.8 kB/s eta 0:00:34
     -- ------------------------------------ 0.7/12.8 MB 349.7 kB/s eta 0:00:35
     -- ------------------------------------ 0.7/12.8 MB 349.7 kB/s eta 0:00:35
     -- ------------------------------------ 0.7/12.8 MB 344.4 kB/s eta 0:00:36
     -- ------------------------------------ 0.7/12.8 MB 344.4 kB/s eta 0:00:36
     -- ------------------------------------ 0.8/12.8 MB 336.8 kB/s eta 0:00:36
     -- ------------------------------------ 0.8/12.8 MB 332.0 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/12.8 MB 332.0 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/12.8 MB 332.0 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/12.8 MB 323.4 kB/s eta 0:00:38
     -- ------------------------------------ 0.8/12.8 MB 323.6 kB/s eta 0:00:38
     -- ------------------------------------ 0.8/12.8 MB 323.6 kB/s eta 0:00:38
     -- ------------------------------------ 0.8/12.8 MB 323.6 kB/s eta 0:00:38
     -- ------------------------------------ 0.8/12.8 MB 323.6 kB/s eta 0:00:38
     -- ------------------------------------ 0.8/12.8 MB 308.6 kB/s eta 0:00:39
     -- ------------------------------------ 0.8/12.8 MB 308.6 kB/s eta 0:00:39
     -- ------------------------------------ 0.8/12.8 MB 308.6 kB/s eta 0:00:39
     -- ------------------------------------ 0.8/12.8 MB 308.6 kB/s eta 0:00:39
     -- ------------------------------------ 0.8/12.8 MB 308.6 kB/s eta 0:00:39
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/12.8 MB 287.4 kB/s eta 0:00:42
     -- ------------------------------------ 0.9/12.8 MB 265.9 kB/s eta 0:00:45
     -- ------------------------------------ 0.9/12.8 MB 265.9 kB/s eta 0:00:45
     -- ------------------------------------ 0.9/12.8 MB 265.9 kB/s eta 0:00:45
     -- ------------------------------------ 0.9/12.8 MB 265.9 kB/s eta 0:00:45
     -- ------------------------------------ 0.9/12.8 MB 255.5 kB/s eta 0:00:47
     -- ------------------------------------ 0.9/12.8 MB 255.5 kB/s eta 0:00:47
     -- ------------------------------------ 0.9/12.8 MB 255.5 kB/s eta 0:00:47
     -- ------------------------------------ 0.9/12.8 MB 255.5 kB/s eta 0:00:47
     -- ------------------------------------ 0.9/12.8 MB 246.8 kB/s eta 0:00:49
     -- ------------------------------------ 0.9/12.8 MB 246.8 kB/s eta 0:00:49
     -- ------------------------------------ 0.9/12.8 MB 246.8 kB/s eta 0:00:49
     -- ------------------------------------ 0.9/12.8 MB 246.8 kB/s eta 0:00:49
     -- ------------------------------------ 0.9/12.8 MB 246.8 kB/s eta 0:00:49
     -- ------------------------------------ 0.9/12.8 MB 238.0 kB/s eta 0:00:50
     -- ------------------------------------ 0.9/12.8 MB 238.0 kB/s eta 0:00:50
     -- ------------------------------------ 0.9/12.8 MB 238.0 kB/s eta 0:00:50
     -- ------------------------------------ 0.9/12.8 MB 233.1 kB/s eta 0:00:51
     -- ------------------------------------ 0.9/12.8 MB 233.1 kB/s eta 0:00:51
     -- ------------------------------------ 1.0/12.8 MB 231.9 kB/s eta 0:00:52
     -- ------------------------------------ 1.0/12.8 MB 231.9 kB/s eta 0:00:52
     -- ------------------------------------ 1.0/12.8 MB 231.9 kB/s eta 0:00:52
     -- ------------------------------------ 1.0/12.8 MB 227.4 kB/s eta 0:00:53
     -- ------------------------------------ 1.0/12.8 MB 228.9 kB/s eta 0:00:52
     -- ------------------------------------ 1.0/12.8 MB 228.9 kB/s eta 0:00:52
     -- ------------------------------------ 1.0/12.8 MB 228.9 kB/s eta 0:00:52
     --- ----------------------------------- 1.0/12.8 MB 226.2 kB/s eta 0:00:53
     --- ----------------------------------- 1.0/12.8 MB 226.2 kB/s eta 0:00:53
     --- ----------------------------------- 1.0/12.8 MB 227.6 kB/s eta 0:00:52
     --- ----------------------------------- 1.0/12.8 MB 227.6 kB/s eta 0:00:52
     --- ----------------------------------- 1.0/12.8 MB 227.6 kB/s eta 0:00:52
     --- ----------------------------------- 1.0/12.8 MB 225.1 kB/s eta 0:00:53
     --- ----------------------------------- 1.0/12.8 MB 225.1 kB/s eta 0:00:53
     --- ----------------------------------- 1.1/12.8 MB 223.5 kB/s eta 0:00:53
     --- ----------------------------------- 1.1/12.8 MB 223.5 kB/s eta 0:00:53
     --- ----------------------------------- 1.1/12.8 MB 223.5 kB/s eta 0:00:53
     --- ----------------------------------- 1.1/12.8 MB 223.5 kB/s eta 0:00:53
     --- ----------------------------------- 1.1/12.8 MB 219.1 kB/s eta 0:00:54
     --- ----------------------------------- 1.1/12.8 MB 219.1 kB/s eta 0:00:54
     --- ----------------------------------- 1.1/12.8 MB 219.1 kB/s eta 0:00:54
     --- ----------------------------------- 1.1/12.8 MB 219.1 kB/s eta 0:00:54
     --- ----------------------------------- 1.1/12.8 MB 213.7 kB/s eta 0:00:55
     --- ----------------------------------- 1.1/12.8 MB 213.7 kB/s eta 0:00:55
     --- ----------------------------------- 1.1/12.8 MB 213.7 kB/s eta 0:00:55
     --- ----------------------------------- 1.1/12.8 MB 212.5 kB/s eta 0:00:56
     --- ----------------------------------- 1.1/12.8 MB 212.5 kB/s eta 0:00:56
     --- ----------------------------------- 1.1/12.8 MB 210.7 kB/s eta 0:00:56
     --- ----------------------------------- 1.1/12.8 MB 210.7 kB/s eta 0:00:56
     --- ----------------------------------- 1.1/12.8 MB 209.6 kB/s eta 0:00:56
     --- ----------------------------------- 1.1/12.8 MB 209.6 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 210.4 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 210.4 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 210.4 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 206.4 kB/s eta 0:00:57
     --- ----------------------------------- 1.2/12.8 MB 206.4 kB/s eta 0:00:57
     --- ----------------------------------- 1.2/12.8 MB 207.7 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 207.7 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 206.1 kB/s eta 0:00:57
     --- ----------------------------------- 1.2/12.8 MB 206.1 kB/s eta 0:00:57
     --- ----------------------------------- 1.2/12.8 MB 205.8 kB/s eta 0:00:57
     --- ----------------------------------- 1.2/12.8 MB 207.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.2/12.8 MB 207.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.6 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.6 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.6 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.9 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.9 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     --- ----------------------------------- 1.3/12.8 MB 206.0 kB/s eta 0:00:56
     ---- ---------------------------------- 1.3/12.8 MB 200.3 kB/s eta 0:00:58
     ---- ---------------------------------- 1.3/12.8 MB 200.3 kB/s eta 0:00:58
     ---- ---------------------------------- 1.3/12.8 MB 200.3 kB/s eta 0:00:58
     ---- ---------------------------------- 1.3/12.8 MB 200.3 kB/s eta 0:00:58
     ---- ---------------------------------- 1.3/12.8 MB 196.3 kB/s eta 0:00:59
     ---- ---------------------------------- 1.3/12.8 MB 196.3 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 195.7 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 195.7 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 195.7 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 195.7 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 195.7 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 195.7 kB/s eta 0:00:59
     ---- ---------------------------------- 1.4/12.8 MB 189.5 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.5 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.5 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.0 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.0 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.4 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.4 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.4 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 189.4 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 185.7 kB/s eta 0:01:02
     ---- ---------------------------------- 1.4/12.8 MB 185.7 kB/s eta 0:01:02
     ---- ---------------------------------- 1.4/12.8 MB 186.5 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 186.5 kB/s eta 0:01:01
     ---- ---------------------------------- 1.4/12.8 MB 186.5 kB/s eta 0:01:01
     ---- ---------------------------------- 1.5/12.8 MB 184.4 kB/s eta 0:01:02
     ---- ---------------------------------- 1.5/12.8 MB 184.4 kB/s eta 0:01:02
     ---- ---------------------------------- 1.5/12.8 MB 184.4 kB/s eta 0:01:02
     ---- ---------------------------------- 1.5/12.8 MB 184.1 kB/s eta 0:01:02
     ---- ---------------------------------- 1.5/12.8 MB 184.1 kB/s eta 0:01:02
     ---- ---------------------------------- 1.5/12.8 MB 184.1 kB/s eta 0:01:02
     ---- ---------------------------------- 1.5/12.8 MB 183.1 kB/s eta 0:01:02

In [46]:
nlp = spacy.load("en_core_web_sm")

In [64]:
abstract1 = abstract.abstract.iloc[0]
abstract1

'Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.'

In [51]:
doc1 = nlp(abstract1)

In [53]:
type(doc1)

spacy.tokens.doc.Doc

In [65]:
with open("stopwords.txt", "r", encoding="utf-8") as f:
    stopwords = set(line.strip() for line in f)

print(stopwords)

{'not', 'their', 'how', 'about', 'you', 'did', 'it', 'will', 'they', 'he', 'by', 'no', 'being', 'does', 'than', 'on', 'at', 'yourselves', 'doing', 'through', 'myself', 'yours', 'are', 'whom', 'its', 'which', 'same', 'who', 'few', 'him', 'of', 'most', 'when', 'was', 'and', 'as', 'just', 'is', 'an', 'with', 'why', 'from', 'in', 'ours', 'until', 'don', 'both', 'only', 'your', 'other', 'here', 'do', 'am', 'because', 'into', 'again', 'some', 'but', 'my', 'under', 'during', 'theirs', 'can', 'have', 'me', 'been', 'we', 'were', 'having', 'she', 'this', 'what', 'that', 'own', 'our', 'more', 'should', 'such', 'up', 'ourselves', 'has', 'hers', 'down', 'out', 'themselves', 'once', 'nor', 'between', 'all', 'too', 'i', 'himself', 'them', 'her', 'be', 'a', 'while', 'after', 'further', 'or', 'those', 'before', 't', 'then', 'against', 'below', 'to', 'above', 'herself', 'off', 'there', 'over', 'very', 'for', 'now', 'each', 'his', 'itself', 'yourself', 'where', 'had', 'if', 'so', 'the', 's', 'these', 'any'}

In [70]:
def preprocessing(document):
    
    try: 
        word_set = set()
        document = nlp(document)
        for word in document:
            lemma = word.lemma_.strip().lower()
        
            if (
                lemma
                and lemma not in stopwords
                and word.is_alpha
                and not word.is_punct
                and not word.is_space
            ):
                word_set.add(lemma)
        return word_set
    except:
        return set()

In [72]:
#abstract_reshape = preprocessing()

abstract["processed"] = abstract.abstract.apply(preprocessing)

C:\Users\Mi\AppData\Local\Temp\ipykernel_20400\3746059958.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abstract["processed"] = abstract.abstract.apply(preprocessing)

In [73]:
abstract

,abstract,processed
0,Congress could do much more to protect America...,"{congress, serve, americans, country, could, p..."
1,Christina Iverson and Jeff Chen ring in the Ne...,"{christina, ring, iverson, chen, new, jeff, year}"
2,"All year long, Earth passes through streams of...","{earth, spot, stream, cosmic, major, list, lon..."
3,"Never miss an eclipse, a meteor shower, a rock...","{never, event, eclipse, rocket, astronomical, ..."
4,A year full of highs and lows in space just en...,"{month, high, highlight, full, low, orbit, end..."
...,...,...
16782,"Survivors can get better, but they need help.","{survivor, help, well, get, need}"
16783,While many teams continued to assess the finan...,"{financial, diego, world, team, favorite, pitc..."
16784,Banks have the power to decide whether to let ...,"{power, approach, account, whether, money, sti..."
16785,The new category of ‘clean wines’ is an effort...,"{wellness, healthful, effort, product, wine, c..."
16786,The hackers gained more access than the compan...,"{though, email, hacker, unable, attacker, prev..."